### ISSUE TITLE
Supporting functions that modify JSON values

### ISSUE THREAD

**Issue by adnanoner** [knex/knex#1337]
As of MySQL 5.7.8, MySQL supports a native JSON data type. Is there any chance the functions to manipulate the JSON data type (https://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html) are going to be built into knex? Functions like `JSON_REPLACE` etc.

**Comment by cyberiaa** [comment]
+1, It seems knex.schema still can't create a json column for new versions of MySQL.

**Comment by rhys-vdw** [comment]
@adnanoner @cyberiaa We'd love to support these if anybody has time to add them. As @cyberiaa points out, Knex already supports some JSON stuff for Postgres.

**Comment by elhigu** [comment]
@rhys-vdw there is basically 0 support for json for postgres too... only some filters has been loosened so that `?`, `?|`, `@>` etc. operators can be used with `.where(..., operator, ...)`. 

I moved bug which doesn't allow json columns to be created with mysql to separate issue and left this one to be feature request. 

Problem with most of json stuff is that knex doesn't support references to attributes inside json columns which will be necessary to be able to create more complex json features.

**Comment by tuhoojabotti** [comment]
Yes, I remember making that PR. Better JSON support would be a great addition, but so far I haven't used that many JSON features and more complex things can be achieved with raw queries.

**Comment by elhigu** [comment]
@tuhoojabotti I wrote json support to our orm and then blog post how to do json stuff with postgres https://www.vincit.fi/en/blog/by-the-power-of-json-queries/ pretty much all json query features were implemented with `knex.raw`. 

If you like to check specific how stuff was implemented you can check code from our query builder. They are really straight forward implementations... some times some extensive casting was needed though. Also making efficient indexes for json is a bit tricky time to time :)

**Comment by gpetrov** [comment]
@elhigu your JSON queries function seems pretty useful, maybe it is time to add something like this on Knex after all those years :)
and the great JSON support all databases now have.

**Comment by kibertoad** [comment]
@gpetrov PRs would be most appreciated :D

**Comment by gpetrov** [comment]
I think making the JSON compatibility universal for all databases will be a great win for Knex, just as it did on the SQL area.

Currently each database type has its own JSON functions and those are all different, so uniting them in Knex and making them universal will an amazing feature of Knex.

Maybe more people of the core team can join in and make this a core Knex feature.

**Comment by kibertoad** [comment]
@gpetrov Core team is mostly involved in reviewing community contributions, very limited amount of development is happening within it. Everyone is busy :)

**Comment by OlivierCavadenti** [comment]
I see all json databases support and what kind of functions I can implements. I have start with basic functions (jsonSet, jsonReplace, jsonRemove,...).
I just want to open here a discussion about jsonPath format to specify what you want to query.

In MySQL, SQLite and Oracle the jsonPath standard is used.
In Postgres and SQLServer, syntax are totally different.

So I have two choices :
- use jsonPath standard in all json functions. To query Postgres and SQLServer, the idea is to convert jsonPath in postgres and sqlserver expressions.
- use json path for MySql, SQLite and Oracle, and dedicated languages for Postgres and SQLServer.

I think the first option is the best option, because the user just use the json path standard and dont need to learn two other path languages. It need some extra work, I need to check if all functions in json path standard can be converted in Postgres and SQL server path languages.

Second option is more simple to implements, but you lose path expression abstraction and you need to use 3 differents path languages in knex when you will use json functions depending of dialect...

Anyway I want your opinions on this subject.

**Comment by gpetrov** [comment]
I would definitely vote for using a jsonpath expressions to preserve the common usage between different databases. That is the main ideology of Knex - use common syntax no matter the database.

And if native syntax is needed, we can always turn the .raw syntax.

**Comment by OlivierCavadenti** [comment]
I think we can close this since a PR is merged. But I will be happy if anyone open other issues to add another json functions,.
