### ISSUE TITLE
Get Columns with an Alias

### ISSUE THREAD

**Issue by chimmelb** [knex/knex#139]
While reading over the docs, I didn't see the ability to query column names with an alias. `SELECT t1_first_name as first from table1`. Handy to have when inheriting someone else's database.

As a suggestion, `.columnAlias( { t1_first_name : "first", t1_last_name : "last" } )` or something similar.

**Comment by mnpenner** [comment]
@tgriesser Isn't splitting on 'as' a bit sketchy? Data can be coming from anywhere, and the query builder should take care to escape everything. What if I have a column named "smart as a fox"?

**Comment by chimmelb** [comment]
This issue is pretty old, and was pre 0.6 when parts of the query builder changed. Unsure how it works now, though "smart as a fox" is a unique column name ; )

**Comment by mnpenner** [comment]
@chimmelb Indeed it is. But the whole reason I'm using a query builder is so that I can build arbitrary queries without worrying about that sort of thing. My application shouldn't break because someone used a 'unique' column or alias name.

As far as I can tell, this functionality has not changed since 2013.
