### ISSUE TITLE
Inconsistent syntax for unique indexes

### ISSUE THREAD

**Issue by goloroden** [knex/knex#1465]
When defining an index on a column, you can chain `index` and `unique` calls.

When defining an index on the table level (e.g., to span it over multiple columns), you can **not** chain the two functions. This leaves the question whether you need to do

``` javascript
table.index([ 'foo', 'bar' ]);
table.unique([ 'foo', 'bar' ]);
```

or only

``` javascript
table.unique([ 'foo', 'bar' ]);
```

?

The documentation unfortunately is not very clear here.

**Comment by jmm** [comment]
`table.unique()` isn't currently documented at all (https://github.com/tgriesser/knex/issues/988). I would think just `table.unique()` though, and that also using `table.index()` would be at best wasteful, unless you wanted to create a second index of a different type† (assuming the database engine allows that), or worse maybe overwrite your unique index because of the automatic naming? That does seem like an unfortunate API inconsistency though. Could probably be solved by making `column.unique()` take the same arguments as `column.index()` and giving `table.index|unique` chained `index|unique` methods. That makes me wonder what Knex does under the hood with `column.unique().index()` though -- create one or two indexes.

†According to [Postgres 9.5 docs](https://www.postgresql.org/docs/9.5/static/indexes-unique.html):
> Currently, only B-tree indexes can be declared unique.
