### ISSUE TITLE
migration transaction

### ISSUE THREAD

**Issue by tkellen** [knex/knex#148]
Is there presently a way to run a migration in a transaction so if it fails it doesn't partially complete?

**Comment by rodhoward** [comment]
I'm still having trouble with partial migrations. my code looks like this:
```
run-file.js:
const readFile = util.promisify(fs.readFile);

module.exports = async (knex, fileName) => {
  const filePath = path.join(__dirname, '../migrations/sqls', fileName);
  const data = await readFile(filePath, { encoding: 'utf-8' });
  return knex.raw(data);
};
```
```
migration:
exports.up = async knex => {
  await knex.transaction(async tran => {
    await runFile(tran, '20190125090040-add-tags-to-roles-up/tags.sql');
    await runFile(tran, '20190125090040-add-tags-to-roles-up/roles_tags.sql');
  });
};
```

The tags sql is applied and the stays in the database even after the roles_tags sql fails.

I'm guessing there is either an issue with the way I'm using transactions or transaction.raw() isn't actually executed in a transaction.  I'm connecting to mysql:
'innodb_version', '8.0.13'
'protocol_version', '10'
'tls_version', 'TLSv1,TLSv1.1,TLSv1.2'
'version', '8.0.13'
'version_comment', 'MySQL Community Server - GPL'
'version_compile_machine', 'x86_64'
'version_compile_os', 'Linux'

Because this is a migration should this already be in a transaction anyway? How does that work?
my knex version is "^0.16.3"

Cheers
Rod

**Comment by zardilior** [comment]
@tgriesser you solution has problems as alterTable and createTable cant be rolled back in mySql as according to @rodhoward

**Comment by mikefrancis** [comment]
I'm using knex 0.21.1 and running the following migration:

```javascript
exports.up = async knex => {
  await knex.schema.alterTable('test', table => {
    table.string('some_column');
  });

  await knex.schema.alterTable('table_that_does_not_exist', table => {
    table.increments('id').primary();
  });
};

```

**Comment by mikefrancis** [comment]
I'm using knex 0.21.1 and running the following migration:

```javascript
exports.up = async knex => {
  await knex.schema.alterTable('test', table => {
    table.string('some_column');
  });

  await knex.schema.alterTable('table_that_does_not_exist', table => {
    table.increments('id').primary();
  });
};

exports.down = () => {};
```

And if migrations were transacted by default, I wouldn't expect `test.some_column` to exist as the statement straight afterwards for `table_that_does_not_exist` fails - but `test.some_column` is there.

Am I missing some config or something?

**Comment by elhigu** [comment]
@mikefrancis if you are using mysql / mariadb transactions really does not work with schema changing queries. See my earlier comment https://github.com/knex/knex/issues/148#issuecomment-457494124
