### ISSUE TITLE
Sqlite schema builder dropForeign is missing

### ISSUE THREAD

**Issue by thetutlage** [knex/knex#1598]
Sqlite `dropUnique` method is missing inside https://github.com/tgriesser/knex/blob/d40e578cadfc12c18ca21fbf436f64f9e36e6079/src/dialects/sqlite3/schema/tablecompiler.js, is it something intentional?

It is inherting from the base `tablecompiler` which throws an error `Method implemented in the dialect driver`.

**Comment by rhys-vdw** [comment]
@thetutlage No, the schema API is just incomplete at the moment.

**Comment by thetutlage** [comment]
@rhys-vdw It seems like there is no easy way to drop `foreign key constraints` from SQLITE.

I am more than happy to submit a PR but want to confirm is there something you have already thought about?

**Comment by elhigu** [comment]
I think @bendrucker started writing new schema building / migration engine long ago, but it didn't get finished after all. He might have knowledge about this.

**Comment by haimich** [comment]
I got the same error using `table.dropForeign('customer_id', 'customer')` with sqlite. Any news on this issue?

**Comment by morungos** [comment]
Ping. This is becoming a blocker for me, as I'm trying to remove a nullable constraint from a foreign key column, and after laboriously copying to a new column and attempting to rename (because you can't modify nullable constraints yet) it seems the foreign key blocks the rename (in dev SQLite anyways), and yet it can't be removed. Do I have to replace the entire table to do this?

**Comment by elhigu** [comment]
@morungos if sqlite supports dropping foreign key constraint you can use `knex.schema.raw` query to do it. Sadly there are still many things that cannot be done through knex.schema APIs.

**Comment by morungos** [comment]
Don't think it does. The general purpose schema mod approach (which seems to be running under the hood) should handle these, but it's generating invalid SQL, specifically a foreign key without a column. It isn't logically very different from dropping a column, though. 

Right now it seems there is no way to achieve this using knex at all. I've had a play with `migrate-db` but immediately got bogged down in weird type differences, so that's not working out well either. Beginning to despair. All I want to do is remove a `NOT NULL` -- really shouldn't be this hard. As things stand it looks like manual migration might be the only option, and that's very icky.

**Comment by morungos** [comment]
Part of the problem is here: https://github.com/tgriesser/knex/blob/master/src/dialects/sqlite3/schema/ddl.js#L157

The replace can lead to a clause that looks like this: `foreign key() references "users"("id")` which is obviously incorrect. I think this is actually a bug, therefore. 

In other words, I can live with dropping a column dropping the associated foreign key, but in SQLite even that doesn't work, but it should and can.

**Comment by elhigu** [comment]
Some stuff is just unnecessary hard to do with sqlite https://www.techonthenet.com/sqlite/foreign_keys/drop.php if there is not yet an issue about implementing dropForeign for it, one could be opened and I would be happy to review PR implementing it. 

If there is some external sqlite helper library (I have never searched if there is one, since I'm not using sqlite a lot) which could be used by knex for sqlite schema changes I would be really happy.

**Comment by morungos** [comment]
Actually, now I look, the main problem is that you can't drop a column in SQLite which has a foreign key. If I could get past that, I'd maybe be able to work around by adding a new column and copying data. That truly is a bug, but it's a different one (the driver is generating bad SQL) so I'll make a new issue for that.

**Comment by datitisev** [comment]
Any updates on this? This is still an issue with Sqlite and the latest knex.

**Comment by kibertoad** [comment]
@datitisev Most likely, nope. Wanna volunteer :)?

**Comment by datitisev** [comment]
@kibertoad I would, but I literally have no Sqlite knowledge, so... I'd rather the developers or some experienced contributors do so, though. 😁

**Comment by rijkvanzanten** [comment]
Seeing SQLite, among other things, doesn't have enough support for "alter column", it's only possible to implement this feature with the whole "create temp -> copy data -> delete old -> rename temp" flow.

I noticed that Knex already has methods to do this flow (`_doReplace` and `reinsertMapped`) in `ddl.js` that's currently used in renaming / dropping columns:

https://github.com/knex/knex/blob/26f3e5d62d291a80f36ae13d6a560b0cd777f836/lib/dialects/sqlite3/schema/ddl.js#L282-L310

Is there any way to reuse the existing methods from DDL in `tablecompiler.js`? @kibertoad @elhigu

**Comment by rijkvanzanten** [comment]
@bendrucker I know this is now 4 years later, and all of this is probably gone.. but did you get anywhere substantial with this new schema building / migration engine back in the day?
