### ISSUE TITLE
Cannot Add Foreign Key Constraint

### ISSUE THREAD

**Issue by node-monk** [knex/knex#245]
When running a migration with the below code, I get an "Cannot add foreign key contraint" message. Anyone point me in the right direction?

``` javascript

exports.up = function(knex, Promise) {
    var defer=Promise.defer();

    knex.schema.createTable('User',function(table){

        //--Create User Table
        table.increments('UserId').primary();
        table.string('username');
        table.string('email',60);
        table.string('password',65);
        table.timestamps();

    })
    .then(function(){
        return knex.schema.createTable('Comment',function(table){

            //--Create Comment Table
            table.increments('CommentId').primary();
            table.string('Comment');

            table.integer('UserId',11).inTable('User').references('UserId');

        });     
    })
    .then(function(){

            defer.resolve();
    });


    return defer.promise;

};

exports.down = function(knex, Promise) {

};  

```

**Comment by kamronbatman** [comment]
As an FYI to future people reading this:
`table.integer('UserId',11).unsigned().inTable('User').references('UserId');`
is now
`table.integer('UserId',11).unsigned().references('UserId').inTable('User');`

**Comment by jmichelin** [comment]
Thank you @batman!

**Comment by JonathanCMitchell** [comment]
Having errors with notNullable(). My foreign keys are always null: 
EX 1:)  ```table.integer('restaurant_id').unsigned().references('id').inTable('Restaurants'); ```
The foreign key('restaurant_id") does not match the 'id' in the table 'Restaurants'. It is simply null, when I attempted to use :
EX2: ) ```table.integer('restaurant_id').unsigned().notNullable().references('id').inTable('Restaurants');```
which threw an Error (cannot add foreign key constraints).

I have seen foreign key creation of this form work if that foreign key is a string, but with an integer referencing the primary key('id). Is it because that Primary key('id') in the parent is not of type integer and is of a default type?
```  table.increments('id').primary(); ```


I have seen foreign keys work when they are a String type, but having an integer type reference to the primary key ('id') in another table throws an error.

When I use EX1) Everything appears to work, but my foreign key does not auto increment, it is simply null the entire time. I also cannot manually increment it using a model function. Did this issue get resolved somewhere? 

Thanks,

**Comment by Juanpam** [comment]
It may be worth clarifying in the docs that the .unsigned() method should be used when defining foreign keys in MySQL. I tried using this with Objection.js and almost gave up because I was only starting and got an error just at first glance. Thought both frameworks were buggy.

**Comment by elhigu** [comment]
> Thought both frameworks were buggy.

@Juanpam no need to use them. PRs are welcome though. Good luck :)

**Comment by Juanpam** [comment]
@elhigu I didn't mean to offend anybody! I'm indeed using the framework 😄. Just thought that for a newcomer, like me, it may be a common problem since relations are a feature commonly used in ORMs and Query builders. Also, MySQL is a common RDBMS.

I can't do a PR right now, but if anyone is interested, I was trying to use XAMPP MySQL while creating the foreign keys. Turns out that when using the .primary() method the created field type is INT(11) unsigned and when you create the reference field using .integer() the resulting field type is INT(11) signed so the foreign key creation fails. @tgriesser fix works wonders, but it would be even better if you could find common fixes/problems like these in the docs.

Anyway, great work!

**Comment by RossComputerGuy** [comment]
I've been running into this exact issue and nothing has fixed it. [My code is here](https://github.com/MidstallSoftware/cerus/blob/master/api/database/index.ts#L39-L139). I'm not sure what I'm doing wrong but I continue to get the foreign key error.

```
error: alter table `accessTokens` add constraint `accesstokens_userid_foreign` foreign key (`userId`) references `users` (`id`) - Can't create table `db`.`accessTokens` (errno: 150 "Foreign key constraint is incorrectly formed") {"code":"ER_CANT_CREATE_TABLE","errno":1005,"sql":"alter table `accessTokens` add constraint `accesstokens_userid_foreign` foreign key (`userId`) references `users` (`id`)","sqlMessage":"Can't create table `db`.`accessTokens` (errno: 150 \"Foreign key constraint is incorrectly formed\")","sqlState":"HY000"
```

If anyone knows the solution to this then that'll be great
