### ISSUE TITLE
whereIn stopped producing parenthesis (in 0.14.5) for pg when a scalar is passed

### ISSUE THREAD

**Issue by Sammons** [knex/knex#2579]
# Environment

Knex version: 0.14.6 (but the issue was introduced in 0.14.5)
Database + version: Postgres 9.6
OS: Windows & Linux

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

`knex.select('foo.*').whereIn('something', 1).toSQL().sql` now produces `select * from "y" where "x" in ?`
and is missing parenthesis that existed in version 0.14.4

2. Error message: An invalid syntax error from the pg lib.

3. Reduced test code, for example
```js
const Knex = require('knex');
const knexPg = Knex({
  client: 'pg'
});
console.log(
  knexPg()
    .select('foo.*')
    .from('foo')
    .whereIn('something', 1)
    .toSQL().sql
)
```

# Missing / erroneus documentation

The previous behavior was undocumented, but no breakage was indicated as this change was undocumented too.

**Comment by Sammons** [comment]
@elhigu Why can't we change what the valid parameters are? It is intuitive that this usage would work; to the extent that I would bet most people never even looked at the docs to figure it out. As an interface knex.js is relatively intuitive, so I'm a little unclear why we can't consider scalars valid and update the docs?

**Comment by elhigu** [comment]
Because passing scalar to that API is unintuitive. It would give a hint that also  `.whereIn('something', 1,2,4)` would be valid arguments (which is an API I don't like either). `Where in` in SQL is operation for an array of value and I believe knex should reflect that in its API like it currently does.

So it all boils down to that in my opinion it is a bad API to allow passing non array literal there. Of course if there are huge demand for that I have to think about it again.
