### ISSUE TITLE
Chained update with increment?

### ISSUE THREAD

**Issue by imiric** [knex/knex#269]
Sorry if I'm missing something, but I can't seem to be able to use `.increment()` along with updating other fields on the table.

For instance, I'd want to do:

``` js
knex('products')
  .whereIn('id', ids)
  .update({'updated_at': new Date()})
  .increment('count', 1);
```

But running this I get:

```
Possibly unhandled Error: The query type has already been set to update
```

I understand why it happens, I just think it would be nice to be able to add other fields to the update.

Alternatively, maybe we could remove `.increment()` altogether and somehow in the `.update()` itself be able to reference the table's columns. Maybe something like:

``` js
knex('products')
  .whereIn('id', ids)
  .update({
    'updated_at': new Date(),
    'count': function() {
      return this + 1;
    }
  });
```

Yeah, not sure about the "this + 1" part, but maybe have another way of saying "the existing column value". This would avoid the need for `.increment()` and `.decrement()`.

I realize I could write this using `.raw()`, but it would be nice to have it in the library.

What do you think?

**Comment by boompig** [comment]
I want to reopen this issue, because it makes sense that chaining `.update()` and `.increment()` together should work, but in fact only increment is applied, and update is disregarded silently.

**Comment by rhys-vdw** [comment]
@boompig Agreed. Also looking at the `increment()` definition it seems it's not possible do multiple increments simultaneously.

[`increment` and `decrement`](https://github.com/tgriesser/knex/blob/775d6c2af7106b38d53083bd5185c189f2fcd01f/lib/query/builder.js#L568-L576) both call [`_counter'](https://github.com/tgriesser/knex/blob/775d6c2af7106b38d53083bd5185c189f2fcd01f/lib/query/builder.js#L710-L721), which is then [compiled as `knex.raw`](https://github.com/tgriesser/knex/blob/775d6c2af7106b38d53083bd5185c189f2fcd01f/src/query/compiler.js#L289-L298). This sets `QueryBuilder._method` to `'counter'` instead of `'update'` so the two are treated as different "types" of queries.

The only advantage I can see to using method `'counter'` instead of `'update'` is allowing different dialects to override the `increments`/`decrements` behaviour specifically. However they all just use `raw('columnName + 1')`.

It's temping to make `increments` and `decrements` as shorthand for `update(knex.raw('columnName + 1'))`, but it seems to be that any actual SQL string generation should be left to the compiler, not the builder. Perhaps [_prepUpdate](https://github.com/tgriesser/knex/blob/775d6c2af7106b38d53083bd5185c189f2fcd01f/src/query/compiler.js#L396-L405) could be modified to read out the stuff set by `_counter()` also...

Anyway, there's something to start with. You're welcome to have a look into it @boompig. I'll accept a PR that corrects this.

**Comment by avimar** [comment]
Yep, just found an `.increment` and `.update` didn't work together. I did it manually with `knex.raw`...

**Comment by WhiteCat6142** [comment]
This issue also occurs on below code.
````js
knex("t").increment("t",1).increment("s",2);
````
The problem might be that *increment()* executes update as soon as it's called.
If I can break compatibity,I'll make it like this.
````js
knex("table").increment("t",1).update();
knex("t").increment("t",1).increment("s",2).update();
knex('products')
  .whereIn('id', ids)
  .increment('count', 1)
  .update({'updated_at': new Date()});
````

**Comment by seiyria** [comment]
just wanted to chime in and say glad that I found this issue - it happened to me as well and it was pretty confusing.

**Comment by boutell** [comment]
In addition, this would be nice:

```
.increment({
  'thumbs_up': 1,
  'thumbs_down': -1
})
```

And it would continue to be a handy option after the more difficult issue of making increment truly chainable is resolved.

**Comment by WhiteCat6142** [comment]
I think It is worth breaking backwards compatibility.

**Comment by teckays** [comment]
Same thing if used in combination with `.decrement()`
```
knex('t').increment('a', 10).decrement('b', 20).where('abc', 1)
// update "t" set "b" = "b" - 20 where "abc" = 1
```

**Comment by stoianchoo** [comment]
Maybe we should write about this in the docs at least.

**Comment by elhigu** [comment]
@stoianchoo please go ahead, PRs to docs are always welcome!

**Comment by HadiAkmal** [comment]
```
LibraryItemDetail.query()
        .where('uuid', borrowDetailUuid)
        .decrement('out_qty', borrowItemUuids.length)
        .increment('return_qty', borrowItemUuids.length);
```

chaining `decrement` with increment also will not work. Only `increment()` will work in the code above

**Comment by ivands** [comment]
What is the status of this?
Would really like to be able to increment multiple fields at once.
Sounds like a no-brainer to me.

**Comment by kibertoad** [comment]
Considering that there are no linked PRs and noone actually reported working actively on this, I would say that status is "Not started". Want to volunteer :)?

**Comment by wubzz** [comment]
PR opened #2740

**Comment by JCMais** [comment]
I suppose this issue can be closed, since the mentioned PR above has been merged.
