### ISSUE TITLE
How to catch constraint errors?

### ISSUE THREAD

**Issue by esamattis** [knex/knex#272]
I need to catch only database constraint errors emitted by `table.unique(["foo", "bar"]);` entry in the schema.

I can do that now with a really hacky Promise#catch(...) predicate:

``` javascript
function isUniqueConstraintError(err){
    if (!err) return false;
    var re = /^duplicate key value violates unique constraint/;  
    return re.test(err.message);                                 
}

MyModel.forge({ foo: "fuz", bar: "fiz" })
.save()
.catch(isUniqueConstraintError, function(err) {
    // Handle the error
});
```

but this is obviously very brittle.

Is there a more robust way to catch this?

**Comment by offlinehacker** [comment]
Wouldn't it be sane for knex to parse errors for you?

**Comment by elhigu** [comment]
@offlinehacker it would be nice, but it is a big task to implement for every database... 

If someone implements it probably parsing errors from each database should be done by some separate package like https://www.npmjs.com/package/pg-error and knex would only map those error formats to be consistent between DB engines.

**Comment by hasahmed** [comment]
Did anything ever come of this? It would be really nice to have errors be consistent across database engines.

**Comment by marianogappa** [comment]
Experimental support would be enough. Even if it solves for 80% of cases, 80% of supported databases, and improves over time. It's better that each and every implementation doing our own :)

**Comment by elhigu** [comment]
@marianogappa you might consider this one, even that it is not done directly on top of knex https://github.com/Vincit/objection-db-errors

@hasahmed for now this is not in scope of knex. 

I think this problem is better to be solved outside of knex since it is potentially huge task to do when trying to support every db driver in the world.

There is no reason why it couldn't be implemented as separate library in which case many projects can benefit from it. In future if that kind of library starts to gain wide support, database driver developers could even add direct support for it which would be the ultimate solution.

**Comment by vishchiv** [comment]
Error object has code property, so I would better try to match errors by error code. 
e.g. for postgres https://www.postgresql.org/docs/9.6/errcodes-appendix.html
