### ISSUE TITLE
Coalesce

### ISSUE THREAD

**Issue by candyapplecorn** [knex/knex#2825]
# Feature discussion / request

1. Explain what is your use case
Using Coalesce to get the first non-null value from a series of expressions.

2. Explain what kind of feature would support this
Implementing SQL's COALESCE

3. Give some API proposal, how the feature should work
I'd like to be able to use coalesce without knex.raw. API might look like this:

knex('Users as U').select(knex.coalesce('U.phone_number', 'U.email', '<no contact info>').as('contact info'))

**Comment by elhigu** [comment]
Seems kind of reasonable for being able to pass very simple coalesce usage, but won't be useful for any more complex cases (also having `.as` support there tells that this is mostly useful in selects).

Like most of the SQL functions I think having this over using `knex.raw('coalesce(??,??,?) as ??' ['U.phone_number', 'U.email', '', 'contactInfo'])`... Also given example syntax will not work, since it cannot differentiate, which one of the passed parameters are identifiers and which ones values (maybe the last one is always value?).

Also should be specified how it works when knex.raw / querybuilder etc. is passed as parameter.

Knex should have some external add-on package, which would implement all this kind of small helpers, that some of the user's want and allow user to choose certain version that works the way they want it to work (basically having own helper library). If we are just having one, which is *not* almost as flexible as `knex.raw`, people will add later on new feature requests to them etc. and handling them takes lots of time especially when one has to think of backwards compatibility when making changes. That time will be off from actually writing really important fixes / features to knex. 

Having support for everyone to select set of helpers they are choosing which supports their use case well and without having to worry about that someone will make breaking change to them in future makes much more sense.

Above spec is way too simple and opinionated to be included in knex.

**Comment by andr3medeiros** [comment]
Suggestion:

```typescript
static ifNull = <T extends BaseModel>(builder: QueryBuilder<T>,
                                      valueIfNull: (otherBuilder: QueryBuilder<T>) => QueryBuilder<T> = (otherBuilder: QueryBuilder<T>) => otherBuilder.select(raw('false')) ) => {
  return builder.unionAll(valueIfNull).limit(1);
}
```

**Comment by elhigu** [comment]
Closing as proposal doesn't seem feasible.
