### ISSUE TITLE
Listen/Notify support

### ISSUE THREAD

**Issue by StephenGentle** [knex/knex#285]
Is support for listen/notify planned at all? I'm using postgres and currently using a mix of directly using the pg library as well as knex. It would be nice to be able to just use knex.

I am subscribing to the notifications as in this example: http://bjorngylling.com/2011-04-13/postgres-listen-notify-with-node-js.html

**Comment by rosendi** [comment]
@tgriesser Could you please provide a simple example?

**Comment by farzher** [comment]
I can't figure out how to use postgres NOTIFY/LISTEN.
I don't want to make a new `pg` client connection, I want to use an existing knex connection.
I just want to just get access to the raw `pg` client and use their driver's support, but idk how.

**Comment by drew-r** [comment]
@farzher - `.client.acquireRawConnection()`

**Comment by mikemfleming** [comment]
@tgriesser your suggestion to implement this yourself makes sense to me. are you specifically recommending that developers use node-postgres to do that? or were you implying that there is a way to do the same with knex?

here is a relevant example of a node postgres implentation.
http://bjorngylling.com/2011-04-13/postgres-listen-notify-with-node-js.html

**Comment by Msea** [comment]
I am trying to use Listen with knex. Using @farzher 's idea I accessed the raw pg connection on app startup and was able to listen on my channels.
However, because I am using a single raw connection and not the connection pool if my database goes down, I lose the connection. Is there a way around this? Can I use my knex connection to poll for when by db comes back up?

**Comment by JonnyLinja** [comment]
I'm implementing the same thing as @farzher and @Msea. I have it working, but am unsure as to two things.

**1. Separate Connection vs Pool**

Are there any disadvantages to acquiring a connection from the pool, listening to the channel, and then releasing the connection back into the pool? Specifically, I see that maintaining a separate connection via `.client.acquireRawConnection()` was recommended by @drew-r. Was this because of side effects, interference with how knex operates, or performance issues?

Example of what I mean as follows.
```
const connection = await knex.client.acquireConnection();
connection.query('LISTEN foo');
connection.on('notification', (msg) => {
   console.log("got " + msg.channel + " payload " + msg.payload);
});
await knex.client.releaseConnection(connection);
```

**2. Dealing with Disconnects**

For database disconnects, are there any better alternatives to repeatedly calling acquireConnection or acquireRawConnection until it succeeds?

For example, one possibility is to fork the library to add a callback to acquireConnection. The callback would be used to listen to the channel if no connection was listening to it already. Honestly, polling knex every couple seconds maybe be less resource intensive overall than this approach. I'm just hesitant to write custom polling for error situations.

**Comment by barroudjo** [comment]
+1 @JonnyLinja 
These are very good questions, I'm also interested in the answers !

**Comment by elhigu** [comment]
1.  if you are not using knex at all why to even get connection from its pool? That code doesn't make sense at all. Also you need to be more careful to return the connection to the pool manually, instead of having knex to get connection, do the query and return the connection automatically.

2. For example doing:  

```
// resolves to true if connection is ok and polls every 1 sec until connection is found
async waitForDbToGetBackOnline() {
    while(true) {
        try {
          let res = await knex.select(knex.raw('1 as one'));
          return res[0].one == 1; 
        } catch (e) {
          await sleep(1000);
        }
    }
}
```

would be better that using acquireConnection, but one can make their own ping query any way they like...

**Comment by JonnyLinja** [comment]
@elhigu Thanks for responding! I might be misunderstanding what you're saying so bear with me. Some context - I have a REST-ish API that uses Knex. The server needs to notify clients of certain changes and I want to do so with websockets via the architecture shown in the diagram at https://devcenter.heroku.com/articles/websockets, just with PostGres Listen/Notify instead of Redis pub/sub.

**1. Separate Connection vs. Pool**

> if you are not using knex at all why to even get connection from its pool?

My thought was that a database connection used for listening to a channel can still be used for API calls. So while I technically don't need Knex to set up the initial `connection.query('Listen foo');` and `connection.on('notification', (msg) => {});`, I can theoretically use a connection from the pool, have it listen to the channel, and then release it back to the pool so it can still be reused for CRUD requests.

> Also you need to be more careful to return the connection to the pool manually, instead of having knex to get connection, do the query and return the connection automatically.

I'm a little confused here. If I understand this correctly, I need the connection itself to do `connection.on('notification', (msg) => {});` when initializing the server and when reconnecting to the database.

Can you outline how I could do `connection.on('notification', (msg) => {});` and `connection.query('Listen foo');` so that it automatically releases into the pool? I'm a fan of the simpler logic, I just don't get it.

**2. Dealing with Disconnects**

> let res = await knex.select(knex.raw('1 as one'))

That's an interesting approach. Are there performance benefits to using a Knex query to see if the database came back online over trying to acquire my own connection? My assumption is that a disconnected database would result in the pool calling acquireConnection each time you query anyways. Does Knex actually keep the connection objects even when disconnected from the database?

Unless there's another way around it, I thought I would still need to acquire a connection anyways to do `connection.on('notification', (msg) => {});`

**Comment by JonnyLinja** [comment]
Also, I just realized that a callback upon a successful connection DOES exist already. https://knexjs.org/#Installation-pooling-afterCreate

I could technically do the `connection.query('Listen foo');` and `connection.on('notification', (msg) => {});` there, I'd just have to ensure that only one connection ever is listening for the channel. Hmm.

**Comment by elhigu** [comment]
You need to do some initial query to make pool to create connections, but I suppose that should work for setting up that channel listening. Also that way is using knex public APIs 👍  

> Does Knex actually keep the connection objects even when disconnected from the database?

No it doesn't. If connection error is got, connection is discarded from pool and new one will be created on next acquire call. I did confuse this issue being just about making sure how to check if DB is online in last comment (since there was earlier talk about it).

If there would be support in other databases for listen, I wouldn't mind having some real API for this too. Anyways your way seems like fine workaround for postgresql. I'm not sure, but maybe listeners should be also be unregistered when connection is broken.

**Comment by JonnyLinja** [comment]
Nod nod. I'm fine with requiring an initial query to set up the listen. Using public APIs and having less polling code running in the background is less risky from a code safety standpoint.

> I'm not sure, but maybe listeners should be also be unregistered when connection is broken.

How would I unregister the listeners? I'm looking through the knex documentation and the documentation of node pg at https://node-postgres.com/api/client and I don't see it. Is there an "off" option?

**Comment by barroudjo** [comment]
@JonnyLinja I tried your proposal with afterCreate, and I noticed a major flaw: it relies on the idea that the pool of connections will always have at least one "active" connection. But a quick test yesterday showed that such is not the case, there are times when there are no active connections in the pool. Hence no listener for a notify sent by the db (and indeed I saw that in this case the server did not receive the db notification)
So I think the only solution to ensure a permanent connection is using either aquireRawConnection or directly node-postgres, with custom code to ensure the connection is active and re-establish it when it is not.

**Comment by JonnyLinja** [comment]
Note, the aforementioned method with afterCreate has a critical flaw and should not be used as is. It operates under the assumption that a connection is lost only when the database server goes down, thereby causing the pool to have 0 connections.

However, it turns out that it is possible for a connection to be lost while the database itself is online. If this happens and there are other connections in the pool, queries can execute without a new listen command being run.

It seems the only feasible solution without modifying the library is the acquireRawConnection method with a timeout in case the connection is dropped.

**Comment by elhigu** [comment]
>... it operates under the assumption that a connection is lost only when the database server goes down, thereby causing the pool to have 0 connections.

What do you mean by that? I didn't see in your code anything, which is checking that pool is empty. Instead of that it sets listening status to `false` when ever the connection in which listening was started is ended because of any reason. Then when next connection is opened by pool, listener is set again (so there might be delay between last listener was closed and next one is opened in case if no new connections are created to the pool). 

As you said, closing / re-opening connections is normal DB behavior and to me your code above did seem to take that into account just fine.

> My original question then stands @elhigu, is there any issue in manually acquiring a connection from the pool, running the listen query, and then releasing it back to the pool?

No, I don't see any special threats in that as far as it is done correctly and that it is not part of public API so it can be broken at any release. There will be some public methods for that at some point though.

Remember that connection you acquire manually from pool can be closed at any time so you need to write your own connection ended recognition / get new one connection set up listeners (maybe free up old ones from old connection) etc. and also when you are trying to get new connection from pool, it might be full and times out etc.

Probably the best thing would be to create separate dedicated knex instance (you can create multiple knex instances and they will have separate pools) just for setting up listeners or to use node-pg directly yo get the connections for that.

**Comment by JonnyLinja** [comment]
The issue with the `afterCreate` approach is that acquiring a connection from the pool does not trigger `afterCreate`. Acquiring a connection does not necessarily involve creating a new connection, it first tries to re-use an existing connection. For example...

**1. INITIAL STATE:**
Say you have the following connections in the connection pool.
> A (idle)
> B (idle, listening on `channel foo`)

**2. CONNECTION B DISCONNECTS:**
Now for whatever reason, connection B goes down. The database IS still available, so connection A is still accessible. The connection pool therefore becomes:
> A (idle)

**3. REQUEST HITS SERVER:**
A request then hits the server, which attempts to read from the database. Knex does its thing.
> A (in use for the query)

**4. REQUEST COMPLETES:**
However, as acquiring `connection A` from the pool does NOT create a new connection, `afterCreate` (where the listen logic is) is never called. After the query finishes, the pool once again looks like
> A (idle)

**5. MULTIPLE REQUESTS OCCUR:**
In order to trigger listening on `channel foo` again, multiple connections would need to occur in close proximity such that `acquireConnection` would create a new one. In this scenario, if TWO requests were to happen, then we'd get:
> A (in use for the query)
> B (in use for the query, listening on `channel foo`)

If the pool has 3 idle connections, none of which are listening to the channel, you'd then need 4 requests to occur in close proximity to trigger the listen again.

**Comment by JonnyLinja** [comment]
@elhigu Gotcha, I'll manually pull from the pool and release back into it, along with some polling code when the connection goes down. My reasoning is that keeping a connection to the database likely has a cost (else I could just maintain over 9000 of them). Given that, it makes sense to have a connection be used for both queries and for listening on a channel.

Thanks again!

**Comment by elhigu** [comment]
> @elhigu Gotcha, I'll manually pull from the pool and release back into it, along with some polling code when the connection goes down. My reasoning is that keeping a connection to the database likely has a cost, so I might as well use one for both querying and listening on a channel.

Cost of one additional connection / connection pool of single connection is irrelevant. I would still suggest to create additional pool (for example with max connections of 2)  for that listener, because that way you can be sure that there is connection slot available in pool when you need it (for example transactions can hog all the connections from pool thus making acquireConnection to fail when you need to re-create listener).

If it is critical that none of the messages from listener are not missed you could even have listeners set for 2 connections all the time and when one goes down, other one might still be available. Anyways I would probably go with as simple solution as possible.

> I was hoping to avoid polling retry logic on the server (I avoid long running asynchronous jobs whenever possible), but it seems like I can't avoid it.

Yup, that cannot be avoided. Someone has to poll and knex is not doing it internally :)

**Comment by JonnyLinja** [comment]
Ah good point about obtaining from and release to the pool, I had not considered the case where the pool maxed out. I think I'll operate without the pool then. `acquireRawConnection` it is.

I'm not certain I want a separate pool for this - even a separate pool does not guarantee that the connection is never dropped, so it adds a lot of complexity. I'd also have to ignore notifications coming off duplicate connections, which adds further complexity. I agree with you that the simplest solution is the best route.

Thanks again @elhigu

**Comment by barroudjo** [comment]
@JonnyLinja I'm very interested in your final solution !

**Comment by fl0w** [comment]
> I'm not sure, but maybe listeners should be also be unregistered when connection is broken.

This shouldn't be necessary @elhigu. [From pg docs](https://www.postgresql.org/docs/current/sql-listen.html):

> A session's listen registrations are automatically cleared when the session ends

**Comment by Msea** [comment]
FWIW I did the polling option. It seemed to work fine, but I haven't gotten to the point of more intensive testing, so I can't say it necessarily solves all the problems. In case you all are interested:


```
const PostgresNotificationListener = (knex) => {
  knex.client.acquireRawConnection().then(connection => {
    doConnectionSetupStuff(connection, knex);
  }).catch((e) => {
    console.log(e);
  });
};
```

```
const reconnectClient = (knex) => {
  const fn = setInterval(function(){
    try {
      knex.client.acquireRawConnection().then(connection => {
         doConnectionSetupStuff(connection, knex);
         clearInterval(fn);
      })
      .catch(e => {
        console.log(e);
      });
    } catch (e) {
      console.log(e)
    }
  }, 3000);
}

function doConnectionSetupStuff(connection, knex) {
  connection.query('LISTEN foo');

  connection.on('notification', (msg) => {
    console.log("got " + msg.channel + " payload " + msg.payload);
  });

  connection.on('end', (err) => {
    reconnectClient(knex);
  })
  connection.on('error', (err) => {
    console.log(err);
  })
```
