### ISSUE TITLE
Float precision and scale ignored in postgres

### ISSUE THREAD

**Issue by storm732** [knex/knex#2945]
# Environment

Knex version: 0.16.2
Database + version: PostgreSQL 10.5
OS: debian 9 stretch

# Bug

When setting **precision** and **scale**  on a float inside a migration, those values are being ignored.
I set it to `table.float('myfloat', 3, 2);` but it was set to 8, 8 in the database.
I didn't get any error message or warning.

This is the exact code for the migration:
```js
exports.up = function(knex, Promise) {
    return knex.schema.withSchema(knex.userParams.schemaName).createTable('chemicals', table => {
       table.increments();
       table.float('concentration', 3, 2);
    });
};
```
Note: `knex.userParams.schemaName` is set to `'public'` in this example

**Comment by kibertoad** [comment]
This one is actually a bit tricky. Currently Knex uses REAL type for floats, even though PostgreSQL supports SQL-standard FLOAT type as well. REAL does not support precision nor scale, FLOAT only supports precision and NUMERIC supports both precision and scale. Our documentation states that precision and scale are supported, and in PostgreSQL case that's clearly wrong currently.

@elhigu What would be your preferable way to address the issue? Switch to FLOAT or NUMERIC? Simply adjust the documentation?

**Comment by kibertoad** [comment]
@storm732 In the mean time, you can use decimal type which should support both scale and precision already.

**Comment by storm732** [comment]
@kibertoad Using decimal solves my problem. Thanks for your answer.

**Comment by elhigu** [comment]
Also I cannot think of any situation why one would like to use any other size of floats which are not 32 bits or 64 bits, since that will give the best precision for storage size (always 4 or 8 bytes for floats). 

Being able to give scale and precision actually hints to the user that type might be implemented as decimal or with some other exact type which doesn't suffer rounding properties of floating points (and doesn't scale as big / as small values either).

**Comment by elhigu** [comment]
documentation issue
