### ISSUE TITLE
Allow migrations to be used without environments

### ISSUE THREAD

**Issue by leore** [knex/knex#328]
Can some add an example of how to add the migrations object. We just switched from .5 to .6 and are having a hard time figuring out what it is not working.

**Comment by kimmobrunfeldt** [comment]
I also define all of my environments with a same config which takes some specifics from env variables. Now I have to do this:

```javascript
module.exports = {
    local: config,
    ci: config,
    dev: config,
    qa: config,
    prod: config
};
```

If a new environment is added, worst case is that migrations fail in the new environment because it's not defined in knexfile.js. It would be best if all the envs should not be defined excplicitly.
