### ISSUE TITLE
Logger argument seems off

### ISSUE THREAD

**Issue by jedborovik** [knex/knex#3363]
# Environment

Knex version: 0.19.0
Database + version: postgres
OS: macOS

If issue is about TypeScript definitions, tag @lorefnon.

# Bug

Logger [type definition](https://github.com/tgriesser/knex/blob/master/types/index.d.ts#L1767-L1774) seems off. It says the argument is a `string`, however, inspecting it is a more complex object, with `sql`, `bindings`, and various other fields (sorry not sure what the correct type is).

**Comment by lorefnon** [comment]
Yeah, there seems to be some inconsistency here. 

The default logger implementation supports logging objects/arrays etc. when level is debug (because it forwards directly to console.log) but not for other levels (because colorette supports only string. 


```
> knex.client.logger.warn({a: 10})
[object Object]
```
I think we can normalize logger to pass the argument through `util.inspect` before applying colorette and update the typedefs to match that of `util.inspect`.

**Comment by kibertoad** [comment]
Released in 0.20.4
