### ISSUE TITLE
Possible SQL injection via the `defaultTo` method

### ISSUE THREAD

**Issue by DarkToast** [knex/knex#3499]
# Environment

Knex version: `0.20.0`
Database + version: `PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit`
OS: `Ubuntu 18.04.3 LTS - LinuxKernel: 4.15.0-66-generic`

# Bug

When creating a table with knex schema and setting a default value to a column, the given parameter will not be escaped and therefore can produce a SQL injection.

Given this code:

    const knex = require('knex')({
        client: 'pg',
        connection: 'postgres:///knex_test'
    });

    knex.schema.createTable('tableName', table => {
        table.string('id_col').notNullable().defaultTo("hello\'); SELECT * FROM pg_database; --");
        table.string('string_col').notNullable();
        table.string('string_col2');
    }).toSQL()[0].sql

Results in this SQL:

    create table "tableName"
    (
        "id_col" varchar(255) not null default 'hello'
    );
    SELECT *
    FROM pg_database; --', "string_col" varchar(255) not null, "string_col2" varchar(255))

I would expect an escaped string  like
 
    create table "tableName"
    (
        "id_col"      varchar(255) not null default '''hello'');SELECT *FROM pg_database; --''',
        "string_col"  varchar(255) not null,
        "string_col2" varchar(255)
    )

see also: section `4.1.2.1. String Constants` on https://www.postgresql.org/docs/12/sql-syntax-lexical.html#SQL-SYNTAX-SPECIAL-CHARS

**Comment by edvardchen** [comment]
Reasonable. I can take it

**Comment by DarkToast** [comment]
Thanks alot.

**Comment by elhigu** [comment]
I'm not convinced at all that these injection holes in schema API should be fixed. Schema calls should never be got directly from user anyways. If this functionality is changed it may cause big problems to people, who has been using `.defaultTo` if their migrations starts to work differently on new machines... this kind of errors are potentially very dangerous, since they might not fail at all in obvious ways and may be found a lot later and only in production servers with database that did run old version of migrations...

For example `.specificType` and I suppose many other methods in schema API are also vulnerable and maybe it is more up to documentation to state clearly that knex.schema.* methods are not SQL injection safe and if people are taking values from user input then they have to validate input by themselves.

**Comment by kibertoad** [comment]
@elhigu If someone relied on part of `.defaultTo` parameter leaking into overall SQL statement, that doesn't sound like something that we should be supporting on encouraging. Isn't it less confusing and more logical if entire parameter is properly escaped in this case?

**Comment by elhigu** [comment]
@kibertoad I'm not saying that it should be encouraged, but I would really not like to make any breaking changes to schema API. 

IMO the whole schema API should be re-implemented (with consistent functionality and same default parameters of different types which does not try to emulate certain type if it does not exist in that dialect etc.) and the old API should be left untouched to maintain support for older code using it (maybe later on as a separate npm package...). 

Or if we really want to patch the old API, then we would first need to support some kind of schema API versioning, so that old code may safely keep on using old API without having to be scared that old migration code starts to create different schema that it used to.
