### ISSUE TITLE
Type Definitions: Awaiting on knex queries violates no-invalid-await rule from SonarTS

### ISSUE THREAD

**Issue by KristjanTammekivi** [knex/knex#3516]
# Environment

Knex version: 0.20.1
Database + version: Postgres 11.4
OS: Ubuntu 18.04

If issue is about TypeScript definitions, tag @lorefnon 

This might be considered a duplicate of #3515, two sides of the same coin sort of deal

# Bug

1. Awaiting on querybuilders/raw queries violates [no-invalid-await](https://github.com/SonarSource/SonarTS/blob/1.9.0.3766/sonarts-core/docs/rules/no-invalid-await.md) rule in tslint-sonarts. This worked on 0.19.2 but not on 0.20.1

2. Refactor this redundant 'await' on a non-promise. (no-invalid-await)

3. await knex('users').select('*').limit(1);

**Comment by lorefnon** [comment]
I think this happens because their `hasThenMethod` [checks](https://github.com/SonarSource/SonarTS/blob/0a71d2479222264b8aa09d7d2d9f8d3490adfb0f/sonarts-core/src/rules/noInvalidAwaitRule.ts#L59) if `.then` property has `ts.SymbolFlags.Method` flag set which won't be in our case because we use a callable interface for the then property of Knex so `then` technically doesn't qualify as a method.

Maybe report this in the SonarTS repo with a minimal reproducer like: 

```ts
interface SomeCallable {
    (cb: Function): Promise; 
} 

interface Builder {
    this: SomeCallable;
}
```

This would have worked before because `QueryBuilder` extended `Promise` interface which had a `then` method.

**Comment by KristjanTammekivi** [comment]
Reported it in sonarts now, closing this one
