### ISSUE TITLE
Transaction doesn't work with map

### ISSUE THREAD

**Issue by derencel20** [knex/knex#3631]
Code:

![image](https://user-images.githubusercontent.com/17394978/72779038-a8cb3d80-3c55-11ea-911e-599fc9abd6fa.png)

Expected output:
Working query

Actual output:
![image](https://user-images.githubusercontent.com/17394978/72779083-cf897400-3c55-11ea-92d4-4210967a4646.png)

Question, Is this really the expected behavior?

**Comment by wubzz** [comment]
Seems correct to me. One of the queries in the map is failing for whatever reason, while another query in the iteration is triggered simultaneously. The failing query in turn issues a rollback due to the error, but the second query is already underway. So it becomes a form of race-condition.

That's how I would interpret the issue given the information you have provided.

Adding a try/catch block in the map should help you find how or why one or more queries are failing.

**Comment by derencel20** [comment]
In the code, I added a return value for ones with errors as `{ }`

![image](https://user-images.githubusercontent.com/17394978/72780268-64da3780-3c59-11ea-97ea-9ba69cf77e4a.png)

This is the result in localhost

![image](https://user-images.githubusercontent.com/17394978/72780367-a4088880-3c59-11ea-9603-36ee4a4181b5.png)


This is the stacktrace
![image](https://user-images.githubusercontent.com/17394978/72780409-c26e8400-3c59-11ea-8b46-a14f7d8e0779.png)

**Comment by elhigu** [comment]
You should not send many queries to same transaction parallel. There is no performance benefit in that since they all have to be executed sequentially through single connection anyway. 

Looks like mssql driver does not buffer multiple requests to the same transaction automatically and throws an error. And it is expected that driver can throw an error if it is used wrong and in that case knex passes that error on.

Also I dont know what mssql does for transaction if one of the queries is failed. For example with pg driver that would cause implicit transaction rollback by default.
