### ISSUE TITLE
Not able to dropForeign PSQL

### ISSUE THREAD

**Issue by sidzan** [knex/knex#3641]
# Environment 

WORKING ON:
Knex version: 0.14.6
Database + version: 9.6.11
OS: ubuntu

ISSUE WITH:
Knex version: 0.14.6
Database + version: 10.4
OS: ubuntu
# Bug

I am currently unable to drop foreign key using `table.dropForeign('controller_user_id')` for db version 10.4

 Error message:
`error: constraint "myi_user_vehicle_controller_user_id_foreign" of relation "myi_user_vehicle" does not exist`

The issue after a bit of digging I found that the key name is different for db_version 10.4. 

The foreign key is named as `myi_user_vehicle_controller_user_id_fkey`. However, knex is trying to drop `myi_user_vehicle_controller_user_id_foreign`.

Is it because of the database version ? or does it have to do something with the config? Any suggestion is much appreciated

**Comment by elhigu** [comment]
As you can see that knex internally creates foreign key name:

https://runkit.com/embed/23yj09pm5mci

Maybe key was created with some earlier version of knex which did generate it with different name. Probably the best shot here is to use knex.schema.raw and drop it manually.

**Comment by ianchanning** [comment]
We have hit this problem too. From what we can tell - this happens if you do a backup via a SQL script and then restore locally. Then the restore SQL script only contains the following kind of SQL statements:

```sql
ALTER TABLE "public"."assessment_flows" ADD FOREIGN KEY ("updated_by") REFERENCES "public"."user_profiles"("id");
```

Note that there is no reference to the foreign key name. The the postgres client itself then creates the foreign keys with the postfix `_fkey`.

Now if you try to run a migration script that drops the foreign key knex will fail because it assumes the FKs have postfix `_foreign`

**Comment by ianchanning** [comment]
Also note, that if you do a binary backup of the database, this isn't a problem because the binary backup contains the foreign key names exactly as they are found in the source database.
