### ISSUE TITLE
Catch executes query twice

### ISSUE THREAD

**Issue by drewhamlett** [knex/knex#367]
If I handle catch in a separate section of code it seems to run the query twice.

``` js
var db = knex('product_group')
        .select('id', 'brand', 'variety')
        .where({
            brand: 'Blah'
        })
        .orderBy('variety');

    db.then(function (groups) {
        return res.json(groups);
    });

    db.catch(next);
```

```
{ __cid: '__cid1',
  method: 'select',
  options: undefined,
  bindings: [ 'Blah' ],
  sql: 'select "id", "brand", "variety" from "product_group" where "brand" = $1 order by "variety" asc' }
{ __cid: '__cid2',
  method: 'select',
  options: undefined,
  bindings: [ 'Blah' ],
  sql: 'select "id", "brand", "variety" from "product_group" where "brand" = $1 order by "variety" asc' }
```

``` js
    var db = knex('product_group')
        .select('id', 'brand', 'variety')
        .where({
            brand: 'Blah'
        })
        .orderBy('variety');

    db.then(function (groups) {
        return res.json(groups);
    }).catch(next);


```

```
{ __cid: '__cid1',
  method: 'select',
  options: undefined,
  bindings: [ 'Blah' ],
  sql: 'select "id", "brand", "variety" from "product_group" where "brand" = $1 order by "variety" asc' }
```

**Comment by jeffwillden** [comment]
According to issue 4760, calling .then() more than once will run the query more than once, even though the documentation says otherwise. Without digging deeper, this appears to be the same or a similar issue, and that calling .then() and also .catch() will run the query multiple times. Either way, issues like these two seem like showstoppers for using knex with promise error handling, or even with complex async/await logic. When writing such logic, there are reasons to await a query in more than one place in the code so that everything runs as expected, even when queries may complete at different times.
#4760
