### ISSUE TITLE
Feature Request: Before insert / update / destroy hooks

### ISSUE THREAD

**Issue by mits87** [knex/knex#3726]
Hi,

is it possible to add before hooks like:
- beforeInsert
- beforeUpdate
- beforeDelete

It seems to me that it is needed for many reason for example if I would like to normalize values globally before modifying the record this functionality can help me a lot..

**Comment by elhigu** [comment]
Try to use some higher level library like objection.js for that, it has all the hooks you need and ways how to organize them so that you can have different hooks for different tables. Also it will not prevent you from writing any kind of SQL you would write with knex. It just makes some common things to be easier to handle than with plain query builder. 

Also some DB drivers has support for transforming input values globally which might work for you.

Or you could try to implement this as a knex plugin if you really don't want to use any higher level library. 

IMO nobody should use knex directly with their application if it is not completely trivial... here is a good read about the subject https://www.jakso.me/blog/objection-to-orm-hatred

Anyways if you really want to push this feature forward, please add some API description also how this should work and what those hooks should exactly do. There might be also some older issues / requests about this same feature, which would be good to link here.
