### ISSUE TITLE
Proposal: declare type conversions

### ISSUE THREAD

**Issue by maximelkin** [knex/knex#3728]
Currently we have bunch of dialects, each behaves on it's own with decimal, bigint, blob, clob

Users should be able to declare for each type expected result type, for example decimal as string or bigint as native js BigInt

**Comment by elhigu** [comment]
I don't see any reason why that should be configurable. If one likes to use some specific type in DB side, then one can use `.specificType` column builder. If one likes to have decimal as string one should use `.string` column instead, since that is what they want. 

One cannot even change those types later on because, migrations has already been ran for example in production and changing types would make old migrations to change and have development DB schema different from production schema...

Sounds like this feature request is trying to patch the fact that current set of column types doesn't have good defaults and in some cases they work really unexpected way.

What we should have is some sane set of column types with sane default values and for example if certain database doesn't have json type, it should throw an error instead of using for example string to represent it.

So there could be few crossdb compatible types and then some database specific types which just are not compatible between dialects at all.

**Comment by elhigu** [comment]
> Users should be able to declare for each type expected result type, for example decimal as string or bigint as native js BigInt

If you mean by this about mapping data returned from database from SQL type -> javascript type, then normal way is to use each SQL driver's own mapping capability to do the work. 

Though I would be happy to see a separate library for abstracting the type mapping setup for every driver, but that would be even more beneficial to be separated to an external npm package. 

It doesn't have anything knex specific in functionality. It could be used by any database library in node world.

**Comment by maximelkin** [comment]
Yes, i mean mapping from sql to js
Knex is about unification, isn't it?

**Comment by maximelkin** [comment]
Also cant imagine such functionality outside knex

**Comment by elhigu** [comment]
> Yes, i mean mapping from sql to js. Knex is about unification, isn't it? 

In those cases where it is applicable.

> Also cant imagine such functionality outside knex

There is nothing that knex can do for this. When results are coming from database driver values has already been converted from SQL types to javascript types. So knex doesn't have enough information how it could interpret those JS types to some other JS types. 

Knex doesn't know anything about DB schema and even if it wouldn't be enough since schema doesn't tell anything about type of result of for example this query `select '1'::bigint`.

External library that abstracts the way how mapping is done for various database drivers in the other hand makes perfect sense. For example like this:
```
const dbresultmapper = require('dbresultmapper'); // please ignore bad name here

dbresultmapper.setup(['pg', 'mysql', 'tedious'], {
  dbresultmapper.sqlTypes.BIGINT: dbresultmapper.jsTypes.STRING,
  dbresultmapper.sqlTypes.TIMESTAMPTZ: dbresultmapper.jsTypes.ISO8061STRING,
  dbresultmapper.sqlTypes.BIGINT: dbresultmapper.jsTypes.CUSTOM(val => {
     return new CustomBigIntClass(val);
  }); 
});

```

Currently everyone needs to write separate code for each database driver for setting up how SQL types are interpret to js types (for example with pg-types).

That would work with any DB library that uses those db drivers under the hood.

**Comment by maximelkin** [comment]
>Knex doesn't know anything about DB schema and even if it wouldn't be enough since schema doesn't tell anything about type of result of for example this query select '1'::bigint.

Some drivers gives metadata about selected data

**Comment by elhigu** [comment]
> > Knex doesn't know anything about DB schema and even if it wouldn't be enough since schema doesn't tell anything about type of result of for example this query select '1'::bigint.
> 
> Some drivers gives metadata about selected data

In that case it could be possible for some drivers 🤷‍♂ In the other hand pretty much every driver allows to declare those mappings. If it is possible to do in driver configuration level it is better to do directly there.

Also it would be a lot slower to create additional pass for running through all the result rows again after driver has already went through them and then run mapping again in knex code. Earlier there was such pass in knex, but it was removed, because it actually caused significant slowdown for knex users in certain cases where people were handling big result sets.

If that kind of mapping configuration npm package is implemented separately, it will be also easier to maintain and it may create its own community around it how helping maintaining it. For example people maintaining database drivers could be interested of keeping that kind of library working with their driver too.

Having it in knex will only burden knex maintainers more and knex test setup is not the best suited for testing that library. Having separate project allows to write better tests for it also for drivers used by custom dialects not included in knex. Also if module supports for all the major drivers and some drivers are not supporting setting up type mappings, then it would be reasonable to request driver maintainers to add support (though I'm not sure if it is even possible for example for sqlite3 since the database internally has only really few SQL types).

I can see only positive effects on implementing this outside of knex.

**Comment by maximelkin** [comment]
Ok, i got it
