### ISSUE TITLE
boolean variable escaping in a raw instruction

### ISSUE THREAD

**Issue by francoisromain** [knex/knex#3772]
Hello and thank you for knex !

Knex version: 0.20.13
Database + version: postgres 12.2
OS: MacOs 10.13.6

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

`knex.raw('? as ??', [true, 'editable'])`: the first variable should be a boolean, but it is a string.

2. Error message

No error message. The type of the variable is not correct

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

```js
const connection = {
  database: 'knex-bug',
  host: process.env.PGHOST,
  password: process.env.PGPASSWORD,
  port: Number(process.env.PGPORT),
  user: process.env.PGUSER
}

const knex = require('knex')({
  client: 'pg',
  connection
})

knex.schema
    .createTable('users', function(table) {
      table.increments('id')
      table.string('user_name')
    })
    .then(function() {
      return knex('users').insert({ user_name: 'Tim' })
    })
  .then(function() {
    return knex('users').select(knex.raw('? as ??', [true, 'editable']))
  })
  .then(function(rows) {
    rows.map(function(row) {
      console.log(row, typeof row.editable)
      // { editable: 'true' } string -> BUG: type should be boolean
    })
  })
  .catch(function(e) {
    console.error(e)
  })
```

**Comment by elhigu** [comment]
This happens, because of the way how node-pg driver creates prepared statements

When

```
knex('users').select(knex.raw('? as ??', [true, 'editable']))
```

is sent to database, driver first creates prepared statement, with one parameter and after that it calls the prepared statement with arguments. 

Prepared statement (created by node-pg driver) doesn't declare typing information for its parameters so the query just doesn't know that the selected literal in boolean SQL type (I cannot remember details how node-pg driver actually sends the data so, I'm sorry for really vague explanation how this happens). 

Anyways knex cannot help you automatically with this, since knex actually passes the boolean as a boolean value to the node-pg driver.

There are 2 ways how you should be a able to work around this 

Cast data in query to boolean:

```
knex('users').select(knex.raw('?::boolean as ??', [true, 'editable']))
```

or hardcode boolean literal to SQL string

```
knex('users').select(knex.raw('true as ??', ['editable']))
```

ps. This could be helped if we add some SQL type wrapper classes for allowing to pass information about SQL types of the parameters in query... though that could require also changes to database drivers and a lot more investigation if it really is viable feature to implement.

**Comment by francoisromain** [comment]
Thank you for the explanation
