### ISSUE TITLE
Incorrect handling of Arrays when inserting or updating a JSONB column. 

### ISSUE THREAD

**Issue by agirorn** [knex/knex#3805]
# Environment

Knex version: 0.20.15
Database + version: PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
OS: Debian

# Bug

## Unable to insert an array into a JSONB column.

```js
const id =  uuid();
db('table').insert({ id, jsonb_column: ['1'] }).then(console.log, console.error);
Promise { <pending> }
> error: insert into "table" ("id", "jsonb_column") values ($1, $2) - invalid input syntax for type json
```

## Unable to update a JSONB column with and array.

```js
const id =  uuid();
db('table').insert({ id }).then(console.log, console.error);+
Promise { <pending> }
db('table').update({ jsonb_column: ['1'] }).where({ id }).then(console.log, console.error);
Promise { <pending> }
> error: update "Promise { <pending> }" set "jsonb_column" = $1 where "id" = $2 - invalid input syntax for type json
```

## Inserting an empty array into a JSONB column causes the array to be converted to an Object.

```js
const id =  uuid();
db('table').insert({ id, jsonb_column: [] }).then(console.log, console.error);+
Promise { <pending> }

db('table').where({ id }).select().first().then(console.log, console.error);
Promise { <pending> }
> {
  id: '70412bc1-c1c7-4e94-9159-741d51233819',
  jsonb_column: {}
}
```

## Updating a JSONB column with an empty array causes the array to be converted to an Object.

```js
const id =  uuid();
db('table').insert({ id }).then(console.log, console.error);+
Promise { <pending> }
db('table').update({ jsonb_column: [] }).where({ id }).then(console.log, console.error);
Promise { <pending> }

db('table').where({ id }).select().first().then(console.log, console.error);
Promise { <pending> }
> {
  id: '70412bc1-c1c7-4e94-9159-741d51233819',
  jsonb_column: {}
}
```

# Table schema
```sql
pg-db=# \d table;
                      Table "public.table"
     Column     |          Type          | Collation | Nullable | Default 
----------------+------------------------+-----------+----------+---------
 id             | uuid                   |           |          | 
 jsonb_column   | jsonb                  |           |          | 

pg-db=# 
```

# What I expect to happen

I expect knex to be clever enough to figure out that I'm inserting or updating a JSONB column with an array and do the necessary conversion.

# The current workaround

Ther is a workaround for this and it is to JSON.stringify(data) before the update or insert.

```js
const id =  uuid();
db('table').insert({ id, jsonb_column: JSON.stringify([]) }).then(console.log, console.error);+
Promise { <pending> }
db('table').update({ jsonb_column: JSON.stringify(['1']) }).where({ id }).then(console.log, console.error);
Promise { <pending> }
```

**Comment by wubzz** [comment]
As described in the documentation regarding `json` column:

> For PostgreSQL, due to incompatibility between native array and json types, when setting an array (or a value that could be an array) as the value of a json or jsonb column, you should use JSON.stringify() to convert your value to a string prior to passing it to the query builder, e.g.

Knex has no clue that you are operating on a `jsonb` column rather than `json`, or any other column-information for that matter. Thus, the same concept applies there.

This is something that *a lot* of people miss and there's a sea of tickets for this. So perhaps it's time to figure out a different approach to this, somehow..

**Comment by elhigu** [comment]
I have already earlier proposed somewhere (possibly multiple times in different forms `knex.lit` might have been one of them) those wrapper classes which can allow user to pass SQL typing information to the queries.  IIRC @wubzz also started implementing some casting support at some point. 

So maybe a feature request to have literal wrappers, which knows how to serialize for example javascript array JSON array so that pg driver / mysql driver can read it in correctly? 

Anyways this issue is already sidetracked from that so easier to write new feature request and refer also this issue there (and also search for old issues for more references where this has been discussed).

> This is something that a lot of people miss and there's a sea of tickets for this. So perhaps it's time to figure out a different approach to this, somehow..

Lets add more tickets to that sea :)

**Comment by wubzz** [comment]
Yeah the casting support would have solved this as well I suppose. It wouldn't have made it 'automatic' as suggested by the ticket, though.

From the drivers [standpoint](https://node-postgres.com/features/types) it seems they simply stringify any object/array that is sent as parameter, as expected. But when it comes to postgres array type it should be `{1, 2, 3}` for arrays and `{{1, 2}, {3, 4}}` for nested structures. Curious how they deal with that type as it's not documented.

**Comment by EduardsE** [comment]
Does JSON.stringify solves your problem? Cause I'm still getting `invalid input syntax for type json`

**Comment by iamrmin** [comment]
Hey guys, did you find any permanent solution?
