### ISSUE TITLE
The best practice for tracking connection establishment

### ISSUE THREAD

**Issue by rngnrs** [knex/knex#3826]
My app is designed to work with DB immediately after launch.
For proper work I usually call a connect function via async/await:
```node.js
// ...
const credentials = {
  connectionString: 'postgresql://localhost/test'
};
const client = await PG.connect(credentials);
// ...and other code that works with `client` goes here and works normally
```
With raw `pg` and without `knex` I would do like that:
```node.js
const { Client } = require('pg');

PG.connect = async function (credentials) {
  const client = new Client(credentials);
  try {
    await client.connect();
  } catch (e) {
    // console.error('Invalid credentials!')
  }
  return client;
};
```
Yep, you would say that I use `Client`, and not `Pool`...
No problem, `pg` has pooling and `pg.Pool.connect()`  too!
```node.js
const { Pool } = require('pg');

PG.connect = async function (credentials) {
  const pool = new Pool(credentials);
  try {
    const client = await pool.connect();
    return client;
  } catch (e) {
    // console.error('Invalid credentials!')
  }
};
```
Also there is a `connect` event:
```node.js
const pool = new Pool();
pool.on('connect', client => {
  client.query('...')
})
```

And with Knex... How can I understand that a connection has been established?
I just need to know, if credentials are correct, without any workarounds.

**Comment by elhigu** [comment]
Connections are created when queries are made to the DB. So if you want at least one connection to be initialized in the pool before you start actually using app you can just do: 

```
await knex.raw('select 1');
```

There is also `afterCreate` callback that can be passed to knex configuration, which can be used to run some code when connection is created for the first time, before it is added to the pool.

> My app is designed to work with DB immediately after launch.

This is usually bad assumption, since connection to database may fail at any time during app execution, so you need to have proper error handling anyways. So usually you can just create a `knex` instance and start doing queries and connections to the DB are created automatically on the background.
