### ISSUE TITLE
Oracle: knex returns null if column value is null. Can it return empty string?

### ISSUE THREAD

**Issue by mike20007** [knex/knex#3883]
# Environment

Knex version: 0.19.5
Database + version: oracle 11g 11.2
OS: Linux

# Question
knex returns null if column value is null. 
Can it return empty string?

  return await knex.raw(
    `
     select USERID, STATUS from users
     where trunc(ENTRYDATE) = ?
     `,dt).then()

Output:
[
    {
        "USERID": "MIKE",
        "STATUS": null
    }
]

Thanks!

**Comment by mike20007** [comment]
Any thought?

**Comment by elhigu** [comment]
Uh so you are asking if knex could modify null from database to be an empty string? Do you want that to happen for every column or for just one column in one query.

Easiest way to do it is to map the result and modify those nulls to be strings.

Another way is to modify your query to convert nulls in some column to strings instead of null. 

For example with some query like:

```
await knex('users').select('*', knex.raw('CONVERTOSTRING(??) as alwaysString', ['columnNameToBeConverted']));
```

**Comment by mike20007** [comment]
Thanks @elhigu.

I need it for all the columns and I did the below.
        let str = JSON.parse(JSON.stringify(data).replace(/\:null/gi, "\:\"\""));
        res.status(200).json(str);

**Comment by elhigu** [comment]
That sounds like a horrible hack, but great if it works for you in this particular case.
