### ISSUE TITLE
feature request: use single transaction for all queries made in a connection

### ISSUE THREAD

**Issue by capaj** [knex/knex#3916]
I am using lambdas in AWS and I had an error like this today:
```
Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```
obviously I had a missing transaction in one of my objection.js queries, but I wondered-wouldn't it be possible to have a knexfile config like:
```js
module.exports = {
  client: 'postgres',
  connection: {
    singleTransaction: true
  }
}
```

where knex would basically create a transaction and passed it around to all my queries without me having to explicitly state it for every one of them? In lambda I always want a behavior like this, because if lambda fails it is retried automatically so it's typical that I put all of my DB work in a single transaction.

Maybe my usecase is not very common, but seeing as lambdas are becoming quite common in the world of cloud computing, maybe supporting this usecase would make sense. WDYT?

**Comment by elhigu** [comment]
You can easily implement this by creating singleton transaction instead of knex instance.

    const trx = knex.transaction();

In handler use trx the same way you would use the knex instance:

     const res = await trx(’users’).where(’id’, 1);

And remember to commit when handler is ready... knex wouldn’t know when to do that anyways so with proposed functionality knex would rollback every time when connection closes unexpectedly.

**Comment by capaj** [comment]
oh right! :facepalm: 
I could initialize my objection with 
```
objection.Model.knex(trx)
```
thanks for that suggestion. That should work just fine!
Thanks. Will give this a shot.
