### ISSUE TITLE
unnecessary deprecated warning

### ISSUE THREAD

**Issue by Truth1984** [knex/knex#3941]
# Environment

Knex version:
Mysql + 0.21.2
OS: ubuntu 16.04

# Bug

when I tried to modify tables with `knex(config)("").schema.table(name, func)`
I received following warning : `calling knex without a tableName is deprecated. Use knex.queryBuilder() instead`.

1. I don't think `queryBuilder` support schema modification
2. it's not necessary to provide a table name since I only want to perform operation on schema level.

**Comment by rijkvanzanten** [comment]
Does it work when using `knex(config).schema.table(name, func)` (without the `("")` part)?

**Comment by Truth1984** [comment]
It works when you have whole functions in one go like so.
but I separated my functions like `let schema = knex(config).schema;`, and it threw a warning.

**Comment by elhigu** [comment]
This should be how to do it:

```
const knex = require('knex')(config);

knex.schema.table(name, func)
```

**Comment by Truth1984** [comment]
Anti pattern

**Comment by elhigu** [comment]
> Anti pattern

Meh... That is just an example of correct usage of knex schema APIs. Nothing to do with design patterns. Would you please elaborate what do you mean?

**Comment by Truth1984** [comment]
Meh...
1. for all these years, I only see something like `builder(name, function() { this.xxx })`, **this** syntax in knex, instead of proper `builder(name, tool=>tool.xxx)`
2. running before initialization. we all expect `let func = knex(config).schema.createTableIfNotExist` should be a function, and it should be passed around or be wrapped by other self-defined functions, however, when you actually call `func(...param)`, it will throw `client.logger` undefined error. which means it is not doing what it suppose to do.
3. throwing createTableIfNotExist warning, and other unnessary warnings, I'm not sure if you are flexing on users or threat them as nine year olds.

**Comment by elhigu** [comment]
1. That is old way and the builder has been provided to functions already years also as a parameter instead of this context. Also that has nothing to do with my answer.
2. I suppose before accessing that `knex` you have imported / required it without any configuration. In my example I required knex and initialized it with configuration before using it. Also when you do `knex(config)` I suppose you are creating a new knex instance with new pool everytime which is completely incorrect way to use knex. You should never remove functions from their object this way `let func = someObject.functionToMove` unless the functions are designed to work that way, because it will loose internal context of the method. Suggesting that this should be working just shows that you really don't know what you are talking about (at least from your writin it is hard to get any other impression).
3. `createTableIfNotExist` should actually be removed, becuase many times it will not do what user would think it does... So one one should never use it unless you really  understand how does it work internally. So far it has been preserved for backwards compatibility. And yes indeed I've been flexing here over 5 years trying to help people to figure out some more obscure things with knex... you need to try harder to get me offended :)
