### ISSUE TITLE
How to create non-parameterized queries? (with bindings inlined)

### ISSUE THREAD

**Issue by pkt-zer0** [knex/knex#3943]
# Environment

Knex version: 0.20.13
Database + version: MSSQL 2017
OS: Windows

# Feature discussion / request

This may or may not be an already supported feature, I didn't quite manage to figure it out so far.

It seems to me that by default, Knex turns every query into a parameterized one, extracting bindings for the values passed in. Sometimes, I don't want to do this, just trigger a query as if I'd typed it in myself (but still safely escaped).

This would be useful for inserting massive amounts of data. For instance, suppose I want to insert 10K rows with 200 columns each. Since MSSQL has a hard limit of 2100 parameters per query, this means I can only insert 10 rows in one call, which means hitting the DB 1000 times. As it turns out, this has a non-trivial per-call overhead, and is super slow (15+ minutes, in my case).

However, MSSQL's upper limit on the rows that can appear in an insert is much higher (1000), so using bigger batches can cut down on the number of calls needed. What I'm doing right now is essentially this:

```
const query = knex.into(table).insert(rows).toString();
await knex.raw(query);
```

Which...
- works!
- seems to be escaped properly
- is 20x faster

So everything is good, except the documentation says that toString() should *not* be used for this purpose, only for debugging. What would then be the suggested alternative? If there isn't one, hopefully I've outlined above why this would be useful to support.

**Comment by elhigu** [comment]
Interpolating bindings safely textual SQL format has been considered out-of-scope for knex so far because that problem is far from trivial to solve. 

In this kind of cases you should first try to figure out why it is so slow and think if there is any other ways to make it faster. If not then you could probably try writing custom validation for parameters in your project and integration tests which makes sure that `.toString` method of inserting data keeps on working for you.

If an external library, which can do interpolation safely for some of the dialects is implemented (with really good tests and some external auditing from experts of each DB and hackers trying to break it) then it will be trivial to implement knex plugin for the problem. 

Also if safe interpolation is provided by DB driver that could be trust worthy if they promise so... 🤔 

So would not like to see this added to knex, because it will open an endless stream of bug reports of it working wrong in the future. Having some other people to handle those bug reports and having someone being an author of that kind of library is a better match for knex.

**Comment by pkt-zer0** [comment]
Sure, that makes sense. Thanks for clearing things up!
