### ISSUE TITLE
How to ignore/exclude the migration and seeding of certain tables

### ISSUE THREAD

**Issue by ksinghgith** [knex/knex#3966]
# Environment

Knex version: 19.4
Database + version: Postgres 12.3
OS: Windows 10

Currently i have to seed all the files even though there is change in a single file csv. Is there a way that we can seed only a specific file while data seeded in the previous/existing files remains as it is in DB. 

Also i wanted to know if we can separate migration & seed folders so that they don't conflict with each other. I want to do this because when i change a particular migration file it throws error specially on foreign key part. So i think if we move it to separate folder than that should solve the error. Please suggest.

**Comment by elhigu** [comment]
Closing as Knex usage questions should be done in gitter or stackoverflow.

You should never change existing migration files unless you are in initial development and have not deployed app to production and you always destroy DB completely and recreate it when app is updated. 

Seed and migrations must be in different directories, otherwise they will be mixed together (see. documentation).

**Comment by kibertoad** [comment]
@ksinghgith You can't do that with migrations, this is not how they are supposed to be used. It is supported for seeds, though. As per documentation:
```
To run a specific seed file, execute:

$ knex seed:run --specific=seed-filename.js
```
