### ISSUE TITLE
Problem with ESM modules

### ISSUE THREAD

**Issue by umaar** [knex/knex#3978]
### Environment

Knex version: 0.21.4
OS: macOS
Node: v14.4.0

```sh
 ➜  ./node_modules/.bin/knex --esm migrate:latest --knexfile knexfile.mjs
Requiring external module /Users/umarhansa/development/project/node_modules/interpret/mjs-stub
TypeError: Cannot read property 'get' of undefined
```

That error is referring to the start of my knex.mjs file which looks like this:

```js
import config from 'config';
const environment = config.get('environment');
```

When I log the value of `config`, it's `undefined` meaning something is broken with ESM via knex. This was working in `0.21.1`

Also please see: https://github.com/knex/knex/issues/3882 - can you include more ESM related tests please? It will help catch these issues before users do, thanks. So far I've experienced quite a few issues already with ESM + knex. Totally appreciate it's still a relatively 'new' thing.

**Comment by kibertoad** [comment]
@D10221 Could you please take a look at this?

**Comment by D10221** [comment]
@umaar 
Hi,  
It seems related to [esm #851](https://github.com/standard-things/esm/issues/851)
'.mjs' limitations are not well documented.
I repro your case , 'mjs' extension might not be well supported by 'esm' , or not work at all 
We might have to fallback to native `import` for that case (`mjs`) 


Would it be possible for you to try your setup with `js' extension instead ?

**Comment by umaar** [comment]
Hi, I will be able to try later and let you know - but just a reminder, this was working in knex version `0.21.1` <- that version also used the `esm` module I think. So possibly something has changed?

Also I haven't tried recently, but a few months ago when I was trying to make ESM work with Knex, I had to call my knexfile `.mjs`. I would've preferred to use `.js` but it didn't work at the time.

**Comment by hydroper** [comment]
I'm having the same issue with latest version. I tried a foo.js at the same directory as knexfile.js.

![image](https://user-images.githubusercontent.com/52384977/90156921-75700d80-dd63-11ea-9de4-b34e512b32c6.png)

![image](https://user-images.githubusercontent.com/52384977/90156934-79039480-dd63-11ea-9ebf-112cbbcfa5d0.png)

**Comment by D10221** [comment]
@umaar   
Yes it did changed.
'esm' wasn't working when the host package is `type:"module"`, latest change is trying to solve that.
I did try latest 'knex' and locally hack the changes back (pseudo revert to previous behavior)  
But is the same result you have reported here when using 'mjs' extension

Also tried with knex@0.21.1

```
$ ./node_modules/.bin/knex  migrate:latest --esm
Requiring external module 
node_modules/interpret/mjs-stub
TypeError: Cannot create proxy with a non-object as target or handler
```
```
$ ./node_modules/.bin/knex  migrate:latest
Requiring external module 
node_modules/interpret/mjs-stub
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: 
knexfile.mjs
    at Module.load (internal/modules/cjs/loader.js:1047:11)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at openKnexfile (.../node_modules/knex/bin/cli.js:26:16)
    at initKnex (.../node_modules/knex/bin/cli.js:49:13)
    at Command.<anonymous> (.../node_modules/knex/bin/cli.js:163:7)
    at Command.listener [as _actionHandler] (.../node_modules/commander/index.js:413:31)
    at Command._parseCommand (.../node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (.../node_modules/commander/index.js:865:18)
```
```
$ ./node_modules/.bin/knex  migrate:latest knex --version
Requiring external module .../node_modules/interpret/mjs-stub
Knex CLI version: 0.21.1
Knex Local version: 0.21.1
```

But your reported problem still there 

##### _Now if I downgrade Node to 12_
Then I can see it working
```
now... if  using node v12.14.0 (npm v6.13.4)
$ ./node_modules/.bin/knex migrate:latest --esm
Already up to date
```
That is false positive, the migration didn't run    
That is because the migration file is also `.mjs`  
even if you added the extension
```
/** @type {import("knex").Config} */
const config = {
  client: 'sqlite3',
  connection: {
    filename: './test.sqlite3',
  },
  useNullAsDefault: true,
  migrations: {
    loadExtensions: ['mjs']
  }
};
/** Named exports: or knex won't find them */
export const { client, connection, useNullAsDefault } = config;
```
Interesting enough, if the migration is 'js' instead of `.mjs`  
It runs successfully
```
rm test.sqlite3 && ./node_modules/.bin/knex migrate:latest --esm
Batch 1 run: 1 migrations
```

What configuration did you use to run succesfully 0.21.1 ?

**Comment by umaar** [comment]
Thanks for looking. All the details of how I got it working in 0.21.1 are in this comment: https://github.com/knex/knex/issues/3882#issue-638047533

Note the 'quick hack' I mentioned also.

The `knexfile.mjs` was an `.mjs` extension, node `v14.1.0` was being used, and it looked like this:

```js
import config from 'config';

const environment = config.get('environment');

const knexConfig = {
	client: 'sqlite3',
	connection: () => ({
		filename: `./path/to/${environment}.sqlite`
	}),
	migrations: {
		directory: './path/to/migrations'
	},
	seeds: {
		directory: `./path/to/seeds`
	},
	useNullAsDefault: true
};

export const {
	client,
	connection,
	migrations,
	seeds,
	useNullAsDefault
} = knexConfig;
```

**Comment by D10221** [comment]
Thanks,
I did look at [#3882](https://github.com/knex/knex/issues/3882#issue-638047533)
Saw you hack , nice :)
Not sure whats the idea behind that mjs sub, why didn't just leave it null/empty like the js extension ? 

I couldn't repro the knex v0.21.1 success , with Node 14
But I found interesting interactions between Node v10/12/14  and `esm`.

According to Node, the 'mjs'  extension can only be 'imported', statically or dynamically
Regardless of where the modules is located 

But the '.js' esm modules are package/location, dependent
because they can't know its a module before its parsed
and because of that, they look at the 'context', to 'require it' or to 'import it'

In principle,,Node dynamic `import` , should be enough to deal with ESM or CJS modules.
But its has way to many restrictions, like ... 

_Can't import! ,  you are not a module!_

And is asynchronous. 

And on top of that, Knex, is a commonjs module and logically, uses 'require' to load the configuration, migrations and seeds.
Synchrously.

So the idea behind the --esm flag is simple , its a shortcut or helper 
to load the external `esm` module loader and 'enhance' the 'require' function, and keep loading Synchrously..

Which in priciple, just works, ... or useto , until Node started 'enhancing' their loader
Or when it doesn't, because of clashing context :(

In practice the `--esm` flag should be left for the MODULE 'js' files, when Node can't dynamically import them, ... most of the times :)  

And eventually, Knex should load the 'mjs' files asynchronously without the external-loader.

**Comment by hydroper** [comment]
I just tried to turn my knexfile.js into CommonJS and, without passing `knex --esm`, I get:

> require() of ES modules is not supported.

I hate Node.js. No V8 snapshotting and no ESMs.

**Comment by aduh95** [comment]
> Can't import! , you are not a module!

FWIW it's possible to use the dynamic `import()` for both ESM and CJS files. That would still be async, but using Top-Level Await (available as of Node.js v14.8.0), it's possible to have a system that support both.

**Comment by guilima** [comment]
Node: v14.8.0
npm: 6.14.6
Knex version: 0.21.3
OS: WSL Ubuntu 18.04.4 LTS
Database + version: PostgresQL 11.7

I'm facing a similar situation, but on [colorette](https://github.com/jorgebucaran/colorette) dependency:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/guilima/www/financial-back/node_modules/colorette/index.js
require() of ES modules is not supported.
require() of /home/guilima/www/financial-back/node_modules/colorette/index.js from /home/guilima/www/financial-back/node_modules/knex/lib/logger.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/guilima/www/financial-back/node_modules/colorette/package.json.
```

To work around the problem It was necessary to use release v1.2.0, because in the latest (v1.2.1) ESM started to be supported https://github.com/jorgebucaran/colorette/pull/45

**Comment by D10221** [comment]
> 
> 
> > Can't import! , you are not a module!
> 
> FWIW it's possible to use the dynamic `import()` for both ESM and CJS files. That would still be async, but using Top-Level Await (available as of Node.js v14.8.0), it's possible to have a system that support both.

Knex has to run on Node 10 , 12 and 14

**Comment by D10221** [comment]
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:  
/home/guilima/www/financial-back/node_modules/colorette/index.js

require() of ES modules is not supported.

require() of /home/guilima/www/financial-back/node_modules/colorette/index.js 

from 

/home/guilima/www/financial-back/node_modules/knex/lib/logger.js 

is an ES module file as it is a .js file   

whose nearest parent package.json contains  
"type": "module"   

which defines all .js files in that package scope as ES modules.    

Instead  
rename index.js to end in .cjs,   
change the requiring code to use import(),  

or remove "type": "module"   
from  
/home/guilima/www/financial-back/node_modules/colorette/package.json

@guilima 

That looks like is Node resolution complaining, not `esm` package or `--esm` flag/feature (that is the same  )

Is your package type 'module' ?

**Comment by guilima** [comment]
> @guilima
> 
> That looks like is Node resolution complaining, not `esm` package or `--esm` flag/feature (that is the same )
> 
> Is your `/home/guilima/www/financial-back` package.json's type='module' ?

Was I mistaken when I thought that the nearest parent package.json should be from knex? Because my project has `ts-node` as dependency and till April they did not fully support ESM. Now they are working on an issue to support ESM https://github.com/TypeStrong/ts-node/issues/1007, but sadly I had a problem trying to implement it.

**Comment by kibertoad** [comment]
@umaar @D10221 0.21.5-next1 is out (the only difference from 0.21.4 being the #3980 included), could you give it a try and see if it makes any of your use-cases better or worse?

**Comment by D10221** [comment]
@kibertoad 
Thanks

@umaar
Note: there is no need for '--esm' flag when using 'mjs' extensions.

**Comment by D10221** [comment]
> > @guilima

> Was I mistaken when I thought that the nearest parent package.json should be from knex?
  
The stacktrace is blaming 'collorette' 
 But the same module is required  by knex internally without a problem 

Thats why I wander what context, triggers that bug?

**Comment by umaar** [comment]
Hey thanks for looking.

Just to clarify, I do have `"type": "module"` in my package.json.

I have tried `0.21.5-next1` as requested:

`./node_modules/.bin/knex --esm migrate:latest --knexfile knexfile.js` (esm flag, .js extension) produces the exact same error as mentioned from the start.

`./node_modules/.bin/knex migrate:latest --knexfile knexfile.js` (no esm flag, js extension) shows the error `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ...knexfile.js`

`./node_modules/.bin/knex --esm migrate:latest --knexfile knexfile.mjs` (esm flag, .mjs extension):  produces the exact same error as mentioned from the start.

` ./node_modules/.bin/knex migrate:latest --knexfile knexfile.mjs` (no esm flag, .mjs extension): complains about my migration `export function up(knex) {
^^^^^^ SyntaxError: Unexpected token 'export'`

---

I have to go back to the old version `0.21.1`. It's the only way I can get it to work for me. Also note, I'm not doing anything 'fancy' or unique, it's a very plain `knexfile` just importing a module. I haven't looked at Knex's implementation, but would highly recommend making standalone projects to test this all out with, and then using those projects as part of Knex.js tests, since these are probably common patterns many people will be using. Thanks again!

**Comment by hydroper** [comment]
I did fork, changed a piece of knexRepository/bin/cli.js and it worked for me: https://github.com/hydroper/knex But one of the tests fail with this (incompatibility).

**Comment by D10221** [comment]
Sorry to bullet point , but I think , there might be too many mixed concerns/angles to see this through

> Just to clarify, I do have `"type": "module"` in my package.json.

In theory it shoudl be fine.
But you shouldn't need to use 'mjs' extensions when package type is 'module'.
I'll double check node ['module' policies](https://nodejs.org/api/esm.html).

> I have tried `0.21.5-next1` as requested: 
> `./node_modules/.bin/knex --esm migrate:latest --knexfile knexfile.js` (esm flag, .js extension) produces the exact same error as mentioned from the start.  

I Need to dig deeper on MacOS, Could be related to [interpret's issue #65](https://github.com/gulpjs/interpret/issues/65)   

> `./node_modules/.bin/knex migrate:latest --knexfile knexfile.js` (no esm flag, js extension) shows the error `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ...knexfile.js`

That is the expected result, standard NodeJS resolution.  
You can't require a module, that is why the [esm module](https://github.com/standard-things/esm) is there for.  
I found this article, ['Node Modules at War: Why CommonJS and ES Modules Can’t Get Along'](https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1),  that it might explain it better than me :)

 
> `./node_modules/.bin/knex --esm migrate:latest --knexfile knexfile.mjs` (esm flag, .mjs extension): produces the exact same error as mentioned from the start.
>
Currently, That is to be expected,   
I noticed problems running `esm` interop and `mjs`.  
That is why we are falling back to NodeJS own dynamic `import`.  
Could also be related to [interpret's issue #65](https://github.com/gulpjs/interpret/issues/65).

> ` ./node_modules/.bin/knex migrate:latest --knexfile knexfile.mjs` (no esm flag, .mjs extension): complains about my migration `export function up(knex) { ^^^^^^ SyntaxError: Unexpected token 'export'`

Is your migration file a '.js' file ?, just a hunch , I could be completely wrong.
 
> I have to go back to the old version `0.21.1`. It's the only way I can get it to work for me. 

I still have to repro this. 
Will dig deeper on the Mac, it fails the same to me as originally reported issue on CI, Ubuntu, Windows and WSL  

> Also note, I'm not doing anything 'fancy' or unique, it's a very plain `knexfile` just importing a module.

I think I saw you were importing ['config'](https://www.npmjs.com/package/config) right ?
I'll check that.

> I haven't looked at Knex's implementation, 
but would highly recommend making standalone projects to test this all out with, and then using those projects as part of Knex.js tests, since these are probably common patterns many people will be using. Thanks again!

Thanks.

The tests have to reproducible, on CI, automated.

We have currently tested the following scenarios:
```
esm flag and mjs support
    ✓ migrates esm modules (1257ms)
    ✓ migrates esm modules from a module (1306ms)
    ✓ migrate esm module without --esm flag from a module, throws error (179ms)
    ✓ migrates mjs modules (953ms)
    ✓ seeds esm files (943ms)
    ✓ seeds esm files from module (999ms)
    ✓ seed throws when runs "esm" files from "module" without --esm flag (178ms)
    ✓ seeds mjs files (615ms)
```
Working on adding more cases.

All the above tests are run againt its own 'package' folder, like this [one, (knexfile-mjs)](https://github.com/knex/knex/tree/master/test/jake-util/knexfile-mjs)

They are isolated trough node command line.  
In principle, it should be the same as having separate project with Knex installed.

Besides that I personally test it on my own environment, using knex as dependency, on Ubuntu LTE, Windows and WSL.
I need to try more on the Mac I'm affraid :)

**Comment by D10221** [comment]
> it's a very plain `knexfile` just importing a module.

I think this could be it.
And could explain why you had success 0.21.1.  
It seems that the original fix for the 'ERR_REQUIRE_ESM' error.
Came with a regresion for the top level imports.

I can replicate the problem, with top level ESM imports.

This [#3985](https://github.com/knex/knex/pull/3985) seems to fix it;

**Comment by kibertoad** [comment]
@umaar @hydroper Could you please check if 0.21.5-next2 works better for you?

**Comment by hydroper** [comment]
Now it runs the configuration file without undefined import.

**Comment by D10221** [comment]
> 
> 
> Now it runs the configuration file without undefined import.
> 
> ```
> $ knex migrate:rollback --esm
> ```

And that's a good thing right ? :)

Did it rollback?

**Comment by kibertoad** [comment]
0.21.5 is out and it should address all the issue reported so far. Feel free to reopen it if you experience any issues.
