### ISSUE TITLE
Support for importing RowDataPacket and related objects

### ISSUE THREAD

**Issue by lx-mn** [knex/knex#3999]
# Environment

Knex version: 0.21.1
Database + version: -
OS: -

# Feature discussion / request

When post processing knex response, I want to check if some nested value of the result is an instance of `RowDataPacket`. 
For example,
```
const processKnexResponse = (result, queryContext) => {
  // ....
  if ( result[0] instanceof RowDataPacket) {
    // process RowDataPacket
  }
};
```

I am looking for something like,
```const { RowDataPacket } = require("knex");```

Similarly, we can add other constructor functions such as `FieldPacket` as well.

**Comment by elhigu** [comment]
What is `RowDataPacket` ?  Please be really clear and specific what the feature that you are trying to get.

 If it requires knex to wrap all results to that kind of objects it will not going to happen, because performance reasons (that is one place in knex which can double CPU time required to return the query results).

Maybe you can create post process response function that does it for you though.

**Comment by elhigu** [comment]
You are probably trying to use some classes specific to certain DB driver. Those are not common to every driver. Can't you just require those from driver's package?

**Comment by elhigu** [comment]
Turns out it is a mysql specific "class". I don't think that here is anything for knex to provide for this feature. Please check from mysql driver how one should recognize if an object is  RowDataPacket or FieldPacket.
