### ISSUE TITLE
CLI Improvements

### ISSUE THREAD

**Issue by rooftopsparrow** [knex/knex#416]
It would be great to have a way to "dry run" a migration to see what would run as well as a flag to print the SQL for a set of migrations.

For example:

``` bash
$ knex --dry-run migrate:latest
Would migrate <x>
Would migrate <y>

$ knex --dry-run --print-sql migrate:latest
ALTER TABLE ...
DROP TABLE ...
```

That way you could easily see what would happen, and also export the sql to file for other purposes.

Let me know what you think.

**Comment by kabirbaidhya** [comment]
I think this is a nice improvement to have. Why was this closed? 

And, is there any recent update on having this feature? If needed contributions for this, I can give a try and do a PR.

**Comment by elhigu** [comment]
Probably due to inactivity or something like that. Looks like consensus has been that it is ok to implement them, but there might be some problems though like mentioned in https://github.com/tgriesser/knex/pull/1717

So PRs are welcome, but no need to reopen this. Also there were 2 different feature requests in this single issue. Two separate ones would be better to treat both separately.

**Comment by kabirbaidhya** [comment]
Makes sense. I'll give it a try and will do a PR, can have further discussion on the PR itself.

**Comment by unhawkable** [comment]
@kabirbaidhya i am looking forward! have you had any success implementing a dry-run option and showing sql queries without executing them?
