### ISSUE TITLE
Misbehavior between .pluck and .first

### ISSUE THREAD

**Issue by KristjanTammekivi** [knex/knex#4223]
# Environment

Knex version: 0.21.12
Database + version: Postgres 13
OS: Linux

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

Combining .pluck() with .first() yields strange behaviors. If .first() is before .pluck(), then the result is an array of plucked elements. If .first() is before .pluck() then the result is object with the plucked key and value

```typescript
        console.log('first', await db('category').pluck('id').first()); // first { id: 1 }
        console.log('second', await db('category').first().pluck('id')); // second [ 1 ]
```

This is aggravated by the fact that the typing says the return value should be 1 in the first case. For the second the typing matches the result, so that's good at least.

2. Error message

None

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

https://runkit.com/kristjantammekivi/5ffc1b0415718c001a6ce54a

**Comment by KristjanTammekivi** [comment]
So... had a quick look at the code and apparently they're mutually exclusive, which prompts the question of whether or not this should be changed or just the typing should be fixed so you can't chain .first and .pluck
![image](https://user-images.githubusercontent.com/8754356/104165031-7afc7d00-5401-11eb-9191-020872af0789.png)

**Comment by kibertoad** [comment]
@elhigu Do you have an opinion on this?

**Comment by elhigu** [comment]
I kind of hate both of the methods, because even that both of the operations are really trivial to do outside of knex, it is not really obvious what is done in query level when those are added to the builder (first() actually adds limit 1 to the query and pluck is just some postprocessing to the result). I have never used them, basically because I find that my code is more readable without them.

One solution is that `.first` and `.pluck` should not be allowed to used together, because `pluck` nature is that it should work for arrays and `.first` returns a single object. In this case error could be thrown.

Though I suppose those could be made to work together if `.pluck` is applied before the `.first` extracts the only element of the returned array. 

Or we could deprecate both of the methods, since they just do so trivial stuff that could be easily done outside of the knex for example with destructuring and `.map`.

**Comment by adarshmadrecha** [comment]
My 2 cents. We should not deprecate these methods. These are very handy methods.
Just the typing should be fixed so we can't chain `.first` and `.pluck`

**Comment by kibertoad** [comment]
@adarshmadrecha I agree. Both are widely used so removing them at this point doesn't seem helpful. Would appreciate if someone would send in a PR that would throw an error if a combination of `pluck` and `first` is used.

**Comment by elhigu** [comment]
Those should be also easy to implement as knex extensions for providing easy backwards compatibility. But just fixing those will probably be less of hassle.
