### ISSUE TITLE
Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? on OracleDB

### ISSUE THREAD

**Issue by nautilux2** [knex/knex#4255]
# Environment

Node:12.18
Database: Oracle
OS: Linux 

Package:     
    "oracledb": "^4.2.0",
    "graphql": "^15.0.0",
    "knex": "^0.21.1"

I got 
    KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? 
error when multiple single insert query (not batch). How can I resolve this problem

**Comment by elhigu** [comment]
Cannot reproduce. You need to reduce your code so that you can pinpoint the area which causes that error happening. Then there can be various reasons why it happens. For example you might try to create more transactions that connections are available in pool or you might forget to commit them or you might try to doo too many parallel queries or it might be something else completely.

**Comment by swami-sanapathi** [comment]
> you might try to doo too many parallel queries

how to handle them? @elhigu
