### ISSUE TITLE
Is there any chance of seeing more feature-complete Postgres support?

### ISSUE THREAD

**Issue by ffxsam** [knex/knex#4427]
# Environment

Knex version: 0.95.4

# Feature discussion / request

Is there any chance that we'll see more complete support of Postgres when it comes to query-building? There are a few things that aren't possible with knex, such as `UPDATE...FROM` and `DELETE...USING`. It would be great to see these officially included.

**Comment by elhigu** [comment]
APIs for those features should be designed database agnostic way so that they can be implemented easily for most of the supported DBs. Please open separate feature request for each feature and API proposals etc. can be discussed in those separately. 

For update from this is older feature request https://github.com/knex/knex/issues/2796 if someone likes to implement it. PRs would be welcome.

Closing as duplicate / not being proper feature request. 

For "delete using" please one new feature request and investigate a bit if that can be supported by other databases too with some common API.
