### ISSUE TITLE
Knex not working with typescript

### ISSUE THREAD

**Issue by its-me-ilia** [knex/knex#4466]
# Environment

Knex version: 0.95.4
Database: Postgres
OS: Windows

@lorefnon

# Bug

i am writing knex with typescript, while hitting tsc causes bunch of errors in knex/types/index.d.ts, i don't know if bug is with my version or my config but i could not even access knex.tablebuilder and knex.config, when i tried.

Error messages are (few of them): 
Type expected column1: `${TTable1}.${TKey1}`,
';' expected column2: `${TTable2}.${TKey2}`
Declaration or statement expected. ): QueryBuilder<TRecord2, TResult2>;

here is picture of vscode errors in index.d.ts file 

https://ibb.co/9n50kzb

**Comment by mglimmerveen** [comment]
I have the same issue after trying to upgrading knex to 0.95.
After this upgrade I did the following: 
-  I upgraded TypeScript devDependency from 3.8.3 to 4.2.4 
- I also did a global install of typescript, so that tsc -v now gives version 4.2.4
- I changed the knex imports according to the upgrading.md

Do you have any idea as to what may cause this?

**Comment by kibertoad** [comment]
Could someone provide a simple repro for the issue?

**Comment by mglimmerveen** [comment]
You mean creating a test repository and seeing if it reproduces the issue?

**Comment by mglimmerveen** [comment]
By the way, I just found this issue: #4439, where javonclarke apparently solved the issue. I'm gonna ask him there if he has more information.

**Comment by kibertoad** [comment]
@mglimmerveen Repository would be ideal, but a code chunk which fails to compile and versions for knex and TS might suffice too.

**Comment by mglimmerveen** [comment]
The odd thing is that the compilation error appears to be in the knex dependency, so I doubt that it's caused by my code.  It seems to me that it is more likely to be a configuration error somehow. Do you agree?

I also just noticed

The problem is that my package is private and also uses some private dependencies, so I'm not sure if it will be easy to reproduce.  I can try to reproduce it myself in a simpler package, but that may take some time. Hence, I'll try to share the most relevant configuration in the meantime.

Here is my package.json, without the private dependencies:

`  "dependencies": {
    "@feathersjs/feathers": "^4.5.8",
    "amqp-connection-manager": "^3.2.0",
    "amqplib": "^0.5.6",
    "axios": "^0.19.2",
    "cassandra-driver": "^4.5.2",
    "feathers-knex": "^4.0.0",
    "ioredis": "^4.17.3",
    "knex": "^0.95.4",
    "moment": "^2.27.0",
    "pg": "^8.2.1",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@types/amqp-connection-manager": "^2.0.10",
    "@types/amqplib": "^0.5.13",
    "@types/ioredis": "^4.17.4",
    "@types/redis": "^2.8.21",
    "dotenv": "^6.1.0",
    "typescript": "^4.2.4"
  },`

And the compiler options in my tsconfig:

`{
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": "src",
    "types": [
      "jest",
    ],  
    "target": "es2016",
    "module": "commonjs",
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "composite": true,
    "esModuleInterop": true,
    "strict": true,
    "noImplicitAny": false,
    "forceConsistentCasingInFileNames": false,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true, 
    "emitDecoratorMetadata": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
  },`

**Comment by mglimmerveen** [comment]
Ah, I might have solved it...

It seems my root package.json in my monorepo still pointed to TypeScript 3.8.3, so even though tsc -v said it used 4.2.4 and my package itself said it used 4.2.4 it didn't compile correctly. 

Let me solve a few remaining issues and confirm that it is working...

**Comment by kibertoad** [comment]
Yup, that really looks like it. If there are errors shown on knex types themselves, it's 100% a TypeScript version issue.

**Comment by its-me-ilia** [comment]
I have Typescript 4.2.4 installed both globally and locally but it's still throwing errors

**Comment by kibertoad** [comment]
@its-me-ilia Can you provide some repro?

**Comment by its-me-ilia** [comment]
Yea the thing is my code is compiling with no problem, it goes to dist and everything it's just vscode errors and typescript errors in console, so i am almost sure it does not have to do anything with code

**Comment by its-me-ilia** [comment]
some of the errors are: 

Namespace '"__DIR__/node_modules/knex/types/index"' has no exported member 'Raw'.
122   type Raw = RawBuilder | Knex.Raw;

Namespace '"__DIR__/node_modules/knex/types/index"' has no exported member 'JoinClause'.
(table: TableRef<QB>, cb: CallbackVoid<Knex.JoinClause>): QB;

Namespace '"__DIR__/node_modules/knex/types/index"' has no exported member 'QueryBuilder'.
toKnexQuery<T = ModelObject<M>>(): Knex.QueryBuilder<T, T[]>;

**Comment by its-me-ilia** [comment]
Closing because objection can only be integrated with knex 0.95 on version 3, so only option is to downgrade knex, until objection 3.0.0 is released

https://github.com/knex/knex/issues/4389
