### ISSUE TITLE
[Feature]: State assertion, dependency traversal

### ISSUE THREAD

**Issue by chb0github** [knex/knex#4504]
# Environment

Knex version: 0.96.6
Database + version: N/A
OS: N/A

# Feature discussion / request

1. `Explain what is your use case`: *To prevent and detect out-of-tool tampering with the DB* 
2. A metadata table, though useful, is insufficient guarantee that a migration should be run, and will do as expected, and doesn't  supply enough audit information. There are more reliable ways to achieve these goals than merely checking a table entry; we can actually interrogate the DB

3. `Give some API proposal, how the feature should work`
- First, the addition of a `validate` function where in: `const validate = (knex) => {true|false}` - Before the migration is run, the database state is validated. Fundamentally, a DB is a state machine and we need to pre and post assert the state

This allows the tool to pre and post assert the state of the DB, and can be used to validate that a rollback does as intended and is syntactically correct before executing. After all: What good is a rollback function if it doesn't work when you need it!?

- Second: Add a `dependsOn` field that takes an array of script names, or the scripts themselves. Those scripts are resolved against the outstanding scripts, and ordered and executed. If the script is already run as part of a previous migration, then those are removed. This would allow for simultaneous applications 

example migration validator:

```javascript
module.exports = {
  up: (knex) => knex.schema.createTable('states', table => {
    table.text('id').primary()
    table.text('team_id').notNullable().references('installations.id').onDelete('cascade')
    table.timestamps('onboarded_date')
    table.text('account_bind_key')
    table.text('jpd_username')
    table.text('jpd_id').notNullable().references('jfrog_platforms.id')
    table.inherits('common')
  }),
  down: (knex) => knex.schema.dropTable('states'),
  validate: (knex) => knex.schema('information_schema')
    .select('count (*) = 1')
    .from('tables').where({
      table_schema:'public',
      table_name: 'states'
    }),
  dependsOn: [
          require('./001-create-installation'), 
          require('./002-create-jfp')
  ] // 001 already depends on 000 and is transitive
}
```
You can also now validate your whole schema change list and look this code, and the rollback, with:
```javascript
if(!migration.validate(knex))  // first validation must return false
    migration.up()
if(!migrations.validate(knex)) {// if it's still false, then whatever they ran did not do as they have asserted and it's an error
  throw new Error('post up validation failure')
}
migration.down()
if(migration.validate(knex))  // If it now returns true, after reverting, it didn't actually reverse the asserted changes; error
  throw new Error('post rollback validation failure')
migration.up()
if(!migration.validate(knex)) // if should now produce true, and if it doesn't, somehow the script failed. though this shouldn't be possible
  throw new Error('Final up validation failed')
```
Here is some sample migration code I kind of protoyped:
```javascript

const migrate = async (knex) => {
  const migrations = load(`${__dirname}/migrations`);

  // before the run, we remove any that are already done
  const todo = migrations.filter(m => !m.validate(knex)).sort();
  const dependencies = todo.map(m => m.dependsOn).flat().unique().sort().map(d => todo[d]);

  // nest the promises together so they execute in exact order, on error, rollback all previous in reverse order
  const chain = (d1,d2) => d1.up().then(d2.up()).catch(() => Promise.all([].concat(d2.down()).concat(d1.down())))
  const remainder = await dependencies.reduce(chain).then(final => Promise.all(
    // from the todo list, remove all of the run dependencies
    todo.filter(t => dependencies.indexOf(t) < 0).map(m => m.up())
  ))
  const groups = migrations.groupBy(migration => migration.validate(knex)) // true means successfully applies
  return groups
};
```

With this approach you can verify the rollbacks are correct and be much more resilient to tampering because it relies on the actual state of the DB. I am not just referring to nefarious actors, but dumb ones as well

**Comment by elhigu** [comment]
I think the first validation part should be pretty trivial to add to the current script just by adding it as a first call in `up()` script.

```
async function validate() {...}

module.exports = {
  up: async (knex) => {
    await validate();
    // do the migration
  }),
  down: async (knex) => {
    await validate();
    // do the rest
  }
}
```

Second part of having dependency tree of migrations that are dependent of each other I cannot think any real usecase for that.

I cannot imagine any cases where all the migrations are not related to each other in some way or another so in that case there would just be DAG style of dependency graph (you would need to be careful of not making cyclic deps)  where in each level of graph one or multiple migrations should be ran in non defined order.

This seems to be highly opinionated, maybe you would like to write a new more complex migration engine for as a separate package? I cannot see any benefit of having this implemented to current migration engine.

Generally it would be better if development migration engine and knex query builder parts would be separate repositories, so that maintainers of migration engine could concentrate just on that single part.

**Comment by chb0github** [comment]
@elhigu 

You're right: It's so trivial. But, your sample above makes it also dead obvious: It's entirely optional and that's the problem

DB Migration tools are about _state management_. By breaking out a predicate function you can have `knex` pre/post assert the state of the DB - this means that there is `no logical chance` that your `down` function does something that your `up` function didn't do. It prevents the catastrophe of needing to do a rollback, only to discover that:

1. The rollback code doesn't, in fact, work and..
2. The rollback had a bug in it and actually deleted unrelated infrastructure. 

This feature is not without precedence. [Liquibase](https://docs.liquibase.com/concepts/advanced/preconditions.html?Highlight=preConditions) does this and highlights why. 

In addition, `preconditions` and their counter part, `postconditions` are [well defined concepts in computing](https://en.wikipedia.org/wiki/Precondition#References) and are required for Google's missions critical systems. In fact, [Guava (google's collection library)](https://github.com/google/guava/wiki/PreconditionsExplained) has these cooked in.

`Pre/post` conditions have a solid foundation in theory and in practice, both specifically in the DB migration world and in the most high-performance computing imaginable. 

As for a dependency graph: There seems to be the assumption that all people managing and modifying the DB code are aware of each other, and that all other teams dependents changes are applied before hand. This is a fair assumption in a small team with a small app. Sadly, large teams and monolithic apps do still exist and any 2 teams may be entirely unaware of each other, but their changes will be piled together. If the combined changes are put together and a dependency no longer exists, then you will break at startup and containerized DB testing won't be necessary. It also has the added advantage of allowing for parallelization since independent changes can run concurrently.

All of this can actually be added in a backward compatible fashion; those wishing preconditions can just add a `predicate` field, and it's presence indicates they want it used.

If you don't see the value of preconditions, then I am not the person to convince you. I have no desire to bike-shed this.

**Comment by elhigu** [comment]
> You're right: It's so trivial. But, your sample above makes it also dead obvious: It's entirely optional and that's the problem

Even if there would be pre/post condition hooks it is entirely optional to write them properly, so additional security is neglible. 

Also it is still trivial to write your own helper layer on top of knex's up/down hooks, where you write migrations like:

```
const secureMigrations = require('./secure-migrations');

module.exports = secureMigrations({
  up: () => {},
  down: () => {},
  prevalidate: () => {},
  postvalidate: () => {}
});
```

So knex provides unopinionated building blocks to implement more opinionated features. I regularly use bunch of project specific helpers customizing migration setup to work well in that particular project.

> Pre/post conditions have a solid foundation in theory and in practice, both specifically in the DB migration world and in the most high-performance computing imaginable.

I like to argue with less abstract things. With absolutely least abstract things imaginable in high performance computing.

> As for a dependency graph: There seems to be the assumption that all people managing and modifying the DB code are aware of each other, and that all other teams dependents changes are applied before hand. This is a fair assumption in a small team with a small app. 

That is not an assumption here.

> Sadly, large teams and monolithic apps do still exist and any 2 teams may be entirely unaware of each other, but their changes will be piled together. If the combined changes are put together and a dependency no longer exists, then you will break at startup and containerized DB testing won't be necessary.

I still don't see how dependency graphs makes that issue any easier.  When changes of some team are merged to main branch, most surely the teams branch contains all the migrations that are needed in the main branch before that. If not, then merge is broken in both approaches.

Though yea there is one corner case where I can see this helping out. If two features are merged to main in correct order, but creation timestamp of the migration files are in wrong order, that would be a problem where dependency describing would be one solution. 

Though in that case one would know it anyways when writing the migration file, that the dependent file has too new timestamp and could just rename their own migration file to have one that is later.
 
>  It also has the added advantage of allowing for parallelization since independent changes can run concurrently.

DDL queries usually doesn't run concurrently and it would be pretty dangerous anyways because many DBs doesn't support transactions for those queries.

> All of this can actually be added in a backward compatible fashion; those wishing preconditions can just add a predicate field, and it's presence indicates they want it used.
> If you don't see the value of preconditions, then I am not the person to convince you. I have no desire to bike-shed this.

👍
