### ISSUE TITLE
MSSQL unicode

### ISSUE THREAD

**Issue by qwerty30112** [knex/knex#4582]
cannot generate N'中文' for MSSQL(SQL Server)

**Comment by kibertoad** [comment]
@qwerty30112 Are you sure this is a problem on knex side? Does using tedious directly work correctly?

**Comment by qwerty30112** [comment]
waht's the relationship between knex and tedious?

**Comment by kibertoad** [comment]
knex uses tedious as a mssql driver.

**Comment by qwerty30112** [comment]
How to do that?

**Comment by qwerty30112** [comment]
But I only want to generate sql string instead of using sql driver to connect to mssql server

**Comment by zeotuan** [comment]
@qwerty30112 can you show some code that reproduce the problem?

**Comment by qwerty30112** [comment]
@zeotuan 
the code is:

import knex_ from 'knex';
const knex = knex_({client: 'mssql'});

let sql = knex('Table').update({FullName:'造字'})
console.log(sql.toString())

------------------------------
the output is:

update [Table] set [FullName] = '造字';select @@rowcount
------------------------------

But I want to generate 
update [Table] set [FullName] = N'造字'
there is a 'N' in the front of the string

reference: https://reurl.cc/bXgYo6

**Comment by zeotuan** [comment]
@qwerty30112 If you set FullName to 造字 shouldn't the output also be 造字? If you want to have N'造字 then the code should be 
```let sql = knex('Table').update({FullName:'N\'造字'})``` since ```'``` is a special character

**Comment by qwerty30112** [comment]
@zeotuan 
But the output is
----
update [Table] set [FullName] = 'N''造字';

**Comment by elhigu** [comment]
```
sql.toString()
```

Is for debugging use only. It doesn't guarantee generating valid / runnable SQL.

When query is executed values are passed as parameter bindings to the query. So what is the problem when you run:

``` 
await knex('Table').update({FullName: '造字'});
```

**Comment by qwerty30112** [comment]
```await knex('Table').update({FullName: '造字'});

**Comment by elhigu** [comment]
Generally knex does not support outputting SQL strings where parameter values are sloppily escaped inside to the outputted SQL string. It works sometimes though, but is not meant for production.

As I said earlier, one has to use the `sql.toSQL().toNative()` to render SQL string + bindings and send queries as parametrized queries to the database. 

Using `.toString()` is not safe because it allows SQL injections (it is not safe with sequel library either). 

Though you could open a feature request to change the way of all JS string type of values are rendered in mssql dialect to be `N'foobar'` instead of `'foobar'` if that works more universally.
