### ISSUE TITLE
Knex: Timeout acquiring a connection

### ISSUE THREAD

**Issue by andersonqi** [knex/knex#4625]
# Environment

Knex version: 0.21.1
Pg version: 8.3.0
Node: 14

# Config

`
connection: {
      connectionString: process.env.DATABASE_URL,
      ssl: {
        rejectUnauthorized: false
      }
    },
    pool: {
      min: 0,
      max: 100,
      afterCreate: (conn: any, done: any) => {
        done();
      }
    },
    acquireConnectionTimeout: 60000
`

# Bug

1. I can't run migrations or seeds.

  When I try to make a request it always responds with

2. Error message

 Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

**Comment by elhigu** [comment]
Cannot reproduce. You need to add complete reproduction code. Check CONTRIBUTING.md.

**Comment by DanielGibbsNZ** [comment]
@andersonqi I've recently encountered a similar issue. Everything was working fine with Node 12 but as soon as I changed to Node 14 I started getting this error. I eventually managed to solve the issue by upgrading `pg` from version 7 to version 8 (as per this issue here: https://github.com/brianc/node-postgres/issues/2388).
