### ISSUE TITLE
Function to reconnect to database

### ISSUE THREAD

**Issue by gaastonsr** [knex/knex#565]
To destroy a knex connection we can make `knex.destroy()` but how we do if we want to reconnect with the same knex instance?

**Comment by gemabarni** [comment]
A real world use case would be serverless functions. I use mines in a way that on each invocation a connection to the database gets established and destroyed at the end. (Leaving the pool open is not an option because it can easily drain the maximal connection count to the database.)

Currently I do this by constructing a new knex instance and close the connection with `knex.destroy()`. I have a relatively big bookshelf schema on top of knex, that has to be rebuilt on each invocation, so it would be nice to reuse it over multiple runs and that is where `knex.reconnect()` would be needed.

**Comment by elhigu** [comment]
@gemabarni actually leaving pool open and limiting pool size of each instance to 1-2 might work better. That way your serverless instances doesn't have to connect / reconnect all the time when reusing instances. 

If you have too many concurrent instances running in either way you'll run out of DB connections (unless your serverless system is leaving some old instances idling to background and will never reuse nor destroy them which sounds pretty unreasonable behavior).

**Comment by gemabarni** [comment]
@elhigu yes, that is a good idea since I don't have that much containers running. I have also tried it out since then, however it turned out that any database connection left open causes timeouts (at least with AWS Lambda), because it does not let the actual invocation terminate. So I guess I don't have many option left, but to close the connections.
