### ISSUE TITLE
knex(options) with the wrong password triggers an ECONNRESET that cannot be handled

### ISSUE THREAD

**Issue by multimeric** [knex/knex#595]
Here's the simplest code I can get that triggers this error:

``` javascript
var knex = require('knex');
var opts = {
    client: "pg",
    connection: {
        host: "127.0.0.1",
        user: "postgres",
        password: "WRONGPASSWROD",
        database: "postgres"
    }
};

try {
    conn = knex(opts);
    console.log("No Error");
}
catch(e){
    console.log("Error");
}
```

Anyone can test it assuming they have a postgres server running locally. The results of this program are:

```
No Error

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
```

Note that it says `No Error`, which means the try catch statement doesn't handle it. I'm assuming what's happening here is that there's a TCP connection to the postgres server that's being prematurely terminated, and dong so asynchronously so that the try/catch doesn't get it.

Could we perhaps provide a callback/promise interface for the connection to the database to allow this to be handled?

**Comment by myndzi** [comment]
This actually runs down to the fact that no error handler is bound to the pg connection object. You can see here:

https://github.com/tgriesser/knex/blob/master/lib/dialects/mysql/index.js#L107

MySQL has a "MySQL specific error handler" (what is MySQL specific about it?)

But...

https://github.com/tgriesser/knex/blob/master/lib/dialects/postgres/index.js#L106

No 'error' event is bound. It is, however, emitted in various cases; I presume the error in the callback is for errors opening the connection, but errors can still be emitted on a previously-opened connection (for example, when it is closed explicitly by the PG server). That's what I was working on testing when I ran into this. I was going to post another issue, but really this issue is the same problem, just under a different name.

It is not a pool problem because the actual raw connection is created in the dialect-specific initialization file in knex proper, which is where the event should be bound (and gracefully close the connection out of the pool)
