### ISSUE TITLE
Auto generating migrations based on defined schema

### ISSUE THREAD

**Issue by rbhalla** [knex/knex#815]
Given a schema file, is there anyway to automatically generate a migration file based on the a diff between the current table state and the schema?

**Comment by StreetStrider** [comment]
Little off-topic: I'm looking for a similar instrument, but implemented in more generic way: it should accept SQL DDL file and a connection to database and synchronizes the db state with schema if possible. If someone knows something like this, please reply.

**Comment by rbhalla** [comment]
That is very similar, as it would require a programmatic way of defining a change in table structure. The only problem with that is data loss, surely you'd want to be able to confirm/edit the change about to happen? That's why I prefer to have a generated migration file just so I can make sure and test on dev/staging before live.

**Comment by StreetStrider** [comment]
@rbhalla,
> surely you'd want to be able to confirm/edit

Yes, you're right. I think such instrument must run only possible and non-data-loss changes and require some form of confirmation in other cases. Maybe a `--dry-run` mode will be good idea too.

This is also very similar to your request, but I don't think such generic instrument has anything with knex directly. So I've noted this as off-topic.

**Comment by mittalyashu** [comment]
Any updates on this feature?

**Comment by elhigu** [comment]
This will never be implemented as part of knex. This is so complicated and huge feature that it would take probably years to make working robust for possible existing schemas. 

This is also unnecessary since on can already rip schema for example from existing postgres database and initialize DB from that. Then one can write knex migrations on top of that base image. No need to start from zero with knex migration files.

Closing old issue which doesn't meet current feature request requirements and is most probably never implemented (especially as part of knex). Not to mention that this kind of code that is used rarely would make knex package size probably a lot  larger that it is currently just for building and running DB queries (maybe even multiple times larger).
