### ISSUE TITLE
limit() not working with del()

### ISSUE THREAD

**Issue by nathanws** [knex/knex#96]
I have a query that returns several rows, but I only want to delete the latest. I tried using:

``` javascript
.where(...).orderBy('date', 'desc').limit(1).del()
```

That deletes all rows that are returned by the where clause, so it seems the `.limit(1)` isn't applied to the query.

I used `knex.raw(...)` for a temporary solution, but it would be much nicer if limit worked on a delete. Not sure if this is a bug or just something that hasn't been implemented yet.

**Comment by Sh4dow** [comment]
Sorry for digging this up but limit is still not working on delete statement and I understand that Postgres is not supporting this. Maybe You should throw some errors on this, I've found this error the hard way. Locking my database for 10 minutes because limit is not working.
I've found Postgres workaround deleting with limit by subquery selecting `id` with limit but ...
```
Error: ER_NOT_SUPPORTED_YET: This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'
```
`.raw` is the only way to be save what You are deleting

**Comment by elhigu** [comment]
Please open a new feature request if you need this functionality to be changed.
