### ISSUE TITLE
Api change in version 1.0?

### ISSUE THREAD

**Issue by epoberezkin** [knex/knex#966]
The fact that knex uses .then() to actually send the query makes it very confusing.

The reasonable expectation of whoever reads the code is that if something is then'ed, it's a promise. Only in case of knex it isn't. It is a query builder object. The fact that the second call to .then() doesn't send the query and returns the same result instead, makes it even more promise-like (although again, it isn't, because nothing happens until .then is called, so the rationale of complying with the standard doesn't make much sense here).

It would be much clearer it there was another method that sends the query and returns the promise. And calling the method again will send the query again - it would allow re-using QB objects. Although it would make it a little bit more verbose (one extra function in the chain), it would make it very clear when what happens and also consistent. Also it would allow handling situations when all I want is sending query and I don't really care about its result. With then I need to handle it by at least passing an empty function.

You could even consider making QB object a function so that instead of calling some method on it, it can be called itself. It would make it almost as concise as it is now. Example:

```
knex('table').select('*')().then(function(rows) {
    console.log(rows);
});
```

And you'll be able to cache queries, like here:

```
var q;

function query() {
    q = q | knex('table').select('*');
    q().then(function (rows) {
        console.log(rows);
    });
}
```

For some complex queries there will be some noticeable performance benefit of doing it.

And you don't even need to break backward compatibility, .then can be supported too, just deprecated.

If you think it is the right thing to do, I could implement.

**Comment by rhys-vdw** [comment]
Hi @epoberezkin. I agree that `QueryBuilder#then` is unusual and a bit confusing. I've thought this since I first started using Knex. I would support a change like this, primarily for clarity.

The downside, as you point out, is that this change would make code more verbose.

> You could even consider making QB object a function so that instead of calling some method on it, it can be called itself.

I'm not sure that it's possible to make the query object a function with properties without reassigning `__proto__`, which I understand is a performance no-no. So an explicit method such as `.ex()` or similar might be preferable here (and less confusing also).

There is a plan to make `QueryBuilder` entirely immutable, in which case there may be a requirement for this kind of change anyway.

Interested to hear @tgriesser's opinion here.

**Comment by epoberezkin** [comment]
If you want to use a real constructor function (with new) then you have to re-assign __proto__ indeed. I've done it and it's not bad in node. We can benchmark it - I think its performance penalty is exaggerated.

We may consider simply returning closures that would have all the methods attached to the instance... But probably reassigning __proto__ is faster.

Extra method is ok too. Can be even ._(), .$() or .q().

**Comment by zacronos** [comment]
+1, this would be a useful change.  More than once I've tried to return a query builder from a promise, and either do more query building or perhaps log `builder.toString()` while troubleshooting, but I can't -- as soon as you try to resolve a promise with a query builder, the query gets sent.  The promise framework things I'm returning a promise rather than a value, and so it goes ahead and `.then()`s my builder.

The workaround I've used is to resolve something like `{ builder: query }` instead of just `query`, but it would be great if that weren't necessary.

**Comment by rhys-vdw** [comment]
@zacronos Completely agree. It's a huge pain, and also means that every Bluebird method needs to be aliased onto `QueryBuilder` (then, tap, filter, map etc).

Also this causes an infinite recursion:

```js
var query = knex('table').where('x', 5);
Promise.bind(query).then(doSomethingWithThis); // I had my reasons...
```

I'm talking to @tgriesser tonight and I'll ask about this issue. I agree that this change would take us to v1.0 which is, admittedly, long overdue.

**Comment by epoberezkin** [comment]
This idea can be taken one step further to help reusing QB objects - parametrised QB objects. Some special strings/constructs can be used to pass a parameter to a query and then it can be passed to function (whether a method or QB itself).

E.g.:

```
var q = knex('table').select('*').where('created_at', '>', '$date');
q({ date: new Date(Date.now() - 86400000) }).then(...);
```

or (to avoid any special characters and occasional escaping):

```
var q = knex('table').select('*').where('created_at', '>', knex.param('date'));
```

but maybe it is too much... :)
In any case making QB not similar to promise will help...

**Comment by elhigu** [comment]
This has been discussed in many issues and especially in async / await world this doesn't work well anymore. Also well seasoned JS developer should be very aware that of course one is not dealing with a promise, but with thenable in case if you are creating query builder and adding more stuff to it on the road. I just stumbled upon this issues while I was looking for those issues where are more discussion about the topic.
