### ISSUE TITLE
Is there a way to set the default timezone of your connection?

### ISSUE THREAD

**Issue by pschuegr** [knex/knex#97]
Also: thanks for all your work on this, tgriesser!

**Comment by roylee0704** [comment]
Does it work by setting the timezone under connection object?

```
  connection: {
    timezone     : 'utc',
  },
```

**Comment by paambaati** [comment]
@roylee0704 It does.

**Comment by dbettini** [comment]
@roylee0704 @paambaati it does not work, since it's a session parameter. You need to use afterCreate

**Comment by elhigu** [comment]
@dbettini it depends on db driver that knex is using. If driver supports attribute `timezone: 'utc'` I'm pretty sure it will be applied to every connection.

**Comment by dbettini** [comment]
@elhigu Which driver supports that attribute in its connection object? Just tested pg, doesn't work with it. Only works using afterCreate.

**Comment by elhigu** [comment]
@dbettini I think some mysql driver might. I know that node-postgres doesn't, I have no idea of the other drivers. You would need to check docs of each driver to find out.

**Comment by Palisand** [comment]
@elhigu I am using the mysql2 driver which is ["mostly API compatible with mysqljs"](https://github.com/sidorares/node-mysql2) and I am specifying `timezone` as `+00:00` since my database's global timezone has been set to `+00:00`. While mysql returns a datetime of `2017-11-20 22:59:44`, knex returns `2017-11-21T03:59:44.000Z` instead of the expected `2017-11-20T22:59:44.000Z`. Even if I set `timezone` to something like `+10:00`, knex returns the same value.

**Comment by nnfans** [comment]
I am using 'pg' driver with afterCreate but every date is still return in 'UTC'

<pre>
pool: {
  afterCreate: function(connection, callback) {
    connection.query('SET time_zone = timezone;', function(err) {
      callback(err, connection);
    });
  }
}
</pre>

**Comment by nusendra** [comment]
mee too @nnfans. After trying in two days, the timezone still in UTC :-(

**Comment by elhigu** [comment]
Are you sure you are using timestamptz type of columns when getting time?

**Comment by nusendra** [comment]
@elhigu 
```
exports.up = function(knex, Promise) {
  return knex.schema.createTable('users', table => {
    table.increments('id');
    table.string('email').unique().notNullable();
    table.string('password').notNullable();
    table.timestamp('created_at', { useTz: true });
    table.timestamp('updated_at', { useTz: true });
  })
};

exports.down = function(knex, Promise) {
  return knex.schema.dropTable('users');
};
```

Here my migration file

**Comment by elhigu** [comment]
Please check from DB schema, thats the ultimate truth. 

Then run in your SQL console:

```
SET time_zone = 'Europe/Helsinki';
select * from users;

```
And see that timezone actually is +2 or +3.

If that all matches up, problem might be 'pg' driver parsing your timestamps to javascript Date objects. You can use pg-types to get them as strings instead. Also remember to check that you are not sending 'SET time_zone = timezone;' to driver in after connect. `timezone` is not a valid timezone.

This is the reason I prefer complete reproduction code with output... otherwise I just need to guess whats wrong if anything.

**Comment by RobertB4** [comment]
For 'pg' users: Setting the time in afterCrete did not work for me, but adding it to the connection object did. I'm using knex v0.20.7.

**Comment by kibertoad** [comment]
@RobertB4 Can you share sample code how you did it?

**Comment by RobertB4** [comment]
@kibertoad here you go:

```
const config: knex.Config = {
  client: "pg",
  connection: {
    port: Number(process.env.PORT),
    user: process.env.USER,
    password: process.env.PASSWORD,
    database: process.env.DB,
    timezone: "Asia/Tokyo",
  },
}
```

**Comment by nnfans** [comment]
@RobertB4 I still had the problem with setting the timezone in connection option object too.
I rather use the frontend to convert the timezone than spending more time figuring out what's the problem

**Comment by HugoLiconV** [comment]
> @kibertoad here you go:
> 
> ```
> const config: knex.Config = {
>   client: "pg",
>   connection: {
>     host: process.env.HOST,
>     port: Number(process.env.PORT),
>     user: process.env.USER,
>     password: process.env.PASSWORD,
>     database: process.env.DB,
>     timezone: "Asia/Tokyo",
>   },
> }
> ```

but what if I want the date in UTC. I tried to set  it  as  `timezone:  "utc"` but it didn't  work

**Comment by OzzyTheGiant** [comment]
Still getting the same error as others are. You know what's even weirder? It's not even UTC time. I have a datetime string set at 17:00:00 in the database, and when Knex fetches it, if it's converting to UTC, it should be 23:00:00 but no, it's 22:00:00, so that means I have to offset by 5 hours when it should be 6 hours.

**Comment by ilanc** [comment]
From my experimentation it appears that `timezone` is used by knex on insert but NOT on select. On select it offsets by your system timezone and you can't change this.

Here's a repo I used for these tests: https://github.com/ilanc/knex-dates. Note the comments in the README in the output section. There's output from a javascript app after using knex to select rows as well as output from doing straight sql queries.

NB for insert the timezone config is used, but note that you specify the timezone in which your code is running NOT the timezone you want to convert dates to. Think of it as an "offset" not as a "target". So setting `timezone: "+00:00"` would mean "don't modify the date on insert or select" - which is probably what is going wrong for the `timezone: "utc"` attempts. 

As pointed out be careful how you create your javascript Date objects:

```js
// I'm running this in South Africa +02:00
new Date("2022-01-01T00:00:00.000") // a local date if TZ not specified = 2021-12-31T22:00:00.000Z
new Date("2022-01-01T00:00:00.000Z") // UTC is Z specified = 2022-01-01T00:00:00.000Z
new Date(2022,0,1) // NB a local date = 2021-12-31T22:00:00.000Z
```
Also be aware that your hosting machine may have a different timezone to your local development machine.

From other comments above it sounds like there's a lot of other things going on. I would recommend a unit test with an assertion on your desired target timezone and assumptions about how knex inserts/selects dates in case this behaviour changes in either the lib or the driver.

**Comment by ilanc** [comment]
Hmm, if my logic above is correct then the only solution is to:
  - avoid specifying the timezone
  - or specify the timezone explicitly but match the system timezone

Note: in either case above knex will write the **local** date string to mysql (see problem below)

You can't resolve this by specifying a different timezone to the system timezone (e.g. UTC when your system is not in UTC)  because this would offset by different amounts on insert & select and hence cause you to receive a different date upon select to that which was inserted.

The problem then is:

- mysql DATETIMEs don't have a timezone
  - if you read and write local dates from 2 systems with different timezones then you will wind up with different dates on each system after select
  - e.g. if you have an ec2 in eu-west-2 (i.e. +00:00) writing dates and a support machine in af-south-1 (i.e. +02:00) reading dates then
    - the ec2 will write "2022-01-01 00:00" to the DB intending it to be "2022-01-01Z"
    - and the support machine will read "2022-01-01 00:00" as "2021-12-31T22:00:00.000Z"
- the only solution to this that I can think of is:
  - set timezone to +0 (so that inserts are not modified)
  - manually offset dates after select by `- systemOffset`

:(

**Comment by ilanc** [comment]
Ok no more coding at 1am. Turns out it was just a bug in my code - I was using a different knex instance to insert vs the one I was using to select. I am now seeing `timezone: "Z"` work correctly on insert and select - utc dates are written to mysql and are deserialized correctly in node on read.

See working version: [final.mjs](https://github.com/ilanc/knex-dates/blob/main/src/final.mjs)

**Comment by Juanpam** [comment]
@ilanc Hey! I've came across this post while looking at how to parse MySQL dates to JS Date objects with UTC timezone. Using timezone: "Z" on the `connection` configuration options of knex worked. 

Would you mind sharing where did you find this?

I also tried using the afterCreate method with the `SET time_zone = "+00:00"` but it did not work. Any clue why the other one works but this one doesn't?

Thanks for the help nonetheless :)

**Comment by ilanc** [comment]
Hi @Juanpam - that's just the standard abbreviation for the UTC timezone aka [zulu time](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators). If you push F12 now in you browser and type the following in the javascript console you can generate an ISO date string:
```js
(new Date).toISOString()
```

**Comment by bojandevic** [comment]
In Postgres setting the timezone is done slightly different, its: `SET timezone = "TIMEZONE"` , without underscore in `timezone`, so this worked for me in Postgres:

```
  pool: {
      afterCreate: function(connection, callback) {
         connection.query('SET timezone = "Europe/London"', function(err) {
            if (err) {
               console.log("Error setting default timezone" + err);
            }
            callback(err, connection);
         });
      }
   }
```

**Comment by ilya-adnymics** [comment]
Unfortunately, the solutions above didn't work for me (in Postgres), neither `afterCreate` hook, nor setting `timezone` on connection. After reading docs for [node-postgres](https://node-postgres.com/features/types#date--timestamp--timestamptz), specifically:

> node-postgres converts DATE and TIMESTAMP columns into the local time of the node process set at process.env.TZ.

so I tried setting `TZ` env variable

```bash
export TZ=UTC
```
(or if you are using .env file, put it there), and it started giving me the dates in UTC, without converting to local.

**Comment by APTy** [comment]
Postgres + knex finally working with `export TZ=UTC` thanks @ilya-adnymics !
